import type { ReactNode } from "react";
import { LocalProfilePanel } from "./LocalProfilePanel";
import type { LocalProfile } from "../lib/profile";

type BackupIcon = (props: { name: "archive" | "check" | "download" | "tape" | "wave"; size?: number }) => ReactNode;

export function BackupPanel({ Icon, backupRoot, profile, onBackupRootChange, onProfileChange, onNotice, onOpenSounds, describePlan }: { Icon: BackupIcon; backupRoot: string; profile: LocalProfile; onBackupRootChange: (value: string) => void; onProfileChange: (profile: LocalProfile) => void; onNotice: (message: string) => void; onOpenSounds: () => void; describePlan: (root: string) => string }) {
  return <div className="tool-body"><label className="backup-root"><span className="section-label">DOSSIER RACINE</span><input value={backupRoot} onChange={(event) => onBackupRootChange(event.target.value)} /><small>Sous-dossiers : machine, firmware, time-capsule-pistes et exports. La Time Capsule contient uniquement Tape et Album.</small></label><LocalProfilePanel profile={profile} onChange={onProfileChange} /><div className="backup-summary"><span className="backup-check"><Icon name="check" size={19} /></span><div><span className="section-label">DERNIÈRE SAUVEGARDE</span><strong>OP-1 · 12 août 2026 à 01:04</strong><small>Vérifiée · 65 fichiers · 269,44 Mo</small></div></div><div className="backup-scope"><strong>Time Capsule Pistes</strong><span>Tape et Album uniquement · pistes, prises et exports audio · sans firmware ni samples utilisateur</span></div><div className="backup-tree"><div><Icon name="archive" size={15} /><strong>OP-1_2026-08-12_01-00</strong></div><span>tape/ · 4 pistes AIFF</span><span>album/ · 2 faces AIFF</span><span>synth/user/ · 44 samples</span><span>drum/user/ · 15 samples</span></div><div className="editor-footer"><span>Copie locale vérifiée par taille et nombre de fichiers</span><button className="primary-action" onClick={() => onNotice(describePlan(backupRoot))}><Icon name="archive" />Préparer une sauvegarde</button></div><div className="backup-actions"><button className="secondary-action" onClick={() => onNotice("La connexion Drive sera proposée après validation du dossier local.")}><Icon name="download" />Connecter Drive</button><button className="secondary-action" onClick={() => onNotice("Time Capsule Pistes : compression de Tape et Album uniquement. Aucun firmware ni sample utilisateur n’est inclus.")}><Icon name="tape" />Time Capsule Pistes</button><button className="secondary-action" onClick={onOpenSounds}><Icon name="wave" />Bibliothèque Sons</button></div></div>;
}
