import type { ReactNode } from "react";
import { SoundControlsPanel } from "./SoundControlsPanel";
import { SoundLibraryIndex } from "./SoundLibraryIndex";
import { SoundPadGrid } from "./SoundPadGrid";

type SoundsIcon = (props: { name: "archive" | "plug"; size?: number }) => ReactNode;

export function SoundsPanel({ Icon, ready, onPreparePack, onTransfer }: { Icon: SoundsIcon; ready: boolean; onPreparePack: () => void; onTransfer: () => void }) {
  return <div className="tool-body"><SoundControlsPanel Icon={Icon} /><SoundPadGrid /><SoundLibraryIndex /><div className="sound-library-head"><div><span className="section-label">BIBLIOTHÈQUE LOCALE</span><strong>OP-1 Music Library</strong><small>Source : sauvegarde OP-1 et dossiers sélectionnés</small></div><span className="midi-badge"><i /> LOCAL</span></div><div className="sound-categories"><div><strong>44</strong><span>Samples synth</span></div><div><strong>15</strong><span>Samples drum</span></div><div><strong>4</strong><span>Pistes Tape</span></div><div><strong>2</strong><span>Faces Album</span></div></div><div className="pack-builder"><div className="mod-section-heading"><div><span className="section-label">PACK À PRÉPARER</span><strong>Pack OP-1 · User Library</strong></div><small>{ready ? "PRÊT" : "BROUILLON"}</small></div><label><input type="checkbox" defaultChecked /> Samples synth · `synth/user`</label><label><input type="checkbox" defaultChecked /> Samples drum · `drum/user`</label><label><input type="checkbox" defaultChecked /> Pistes Tape · `tape`</label><label><input type="checkbox" /> Faces Album · `album`</label></div><div className="editor-footer"><span>{ready ? "Pack vérifié et prêt pour copie" : "Sélection locale · aucune copie exécutée"}</span><button className="primary-action" onClick={onPreparePack}><Icon name="archive" />Préparer le pack</button></div><div className="sound-transfer-panel"><div><span className="section-label">TRANSFERT OP-1</span><strong>Copier les sons préparés</strong><small>La sauvegarde doit être validée dans Sauvegardes avant toute copie.</small></div><button className="secondary-action" onClick={onTransfer}><Icon name="plug" />Préparer le transfert</button></div></div>;
}
