"use client";
import {useState} from "react";
import StudioHeader from "../../StudioHeader";
import "./vault.css";

type Machine="op-1"|"ep-133";
const data={
 "op-1":{name:"OP-1",accent:"blue",image:"/media/teenage-engineering-op-1-pixel-art-music-workstation.jpeg",capacity:"256 MB",used:"184 MB",firmware:"243",folders:[["TAPE","4 pistes · 23:48"],["ALBUM","Side A + Side B"],["DRUM","42 kits"],["SYNTH","68 patches"],["USER","Réglages & presets"]],snapshots:[["17 AOÛT · 11:42","COMPLET","184 MB","VÉRIFIÉ"],["12 AOÛT · 18:06","TAPE + ALBUM","96 MB","VÉRIFIÉ"],["08 AOÛT · 09:31","DRUM + SYNTH","44 MB","VÉRIFIÉ"]]},
 "ep-133":{name:"EP-133 K.O. II",accent:"orange",image:"/media/teenage-engineering-ep-133-ko-ii-pixel-art-sampler.jpeg",capacity:"64 MB",used:"48 MB",firmware:"1.2.4",folders:[["PROJETS","9 projets"],["GROUPES A–D","36 groupes"],["PATTERNS","128 patterns"],["SCÈNES","24 scènes"],["SONS","468 samples"]],snapshots:[["16 AOÛT · 22:18","COMPLET","48 MB","VÉRIFIÉ"],["13 AOÛT · 20:44","PROJET 07","12 MB","VÉRIFIÉ"],["10 AOÛT · 14:05","SONS + PADS","31 MB","VÉRIFIÉ"]]}
};
export default function BackupMachinePage({machine}:{machine:Machine}){const d=data[machine];const [selected,setSelected]=useState(d.folders.map(x=>x[0]));const [message,setMessage]=useState("MACHINE PRÊTE");const toggle=(name:string)=>setSelected(v=>v.includes(name)?v.filter(x=>x!==name):[...v,name]);return <main className={`vault-page machine-vault ${d.accent}`}><StudioHeader/><header className="machine-vault-head"><div><a href="/outils/sauvegardes">← CHOISIR UNE MACHINE</a><small>VAULT-01 · {d.name}</small><h1>Sauvegarde<br/><em>{d.name}</em></h1><p>Créer une copie complète ou sélectionner uniquement les éléments utiles.</p></div><div className="machine-device"><img src={d.image} alt={d.name}/><span>● CONNECTÉE · LECTURE SÛRE</span></div></header><section className="backup-console"><aside className="machine-summary"><h2>ÉTAT MACHINE</h2><div className="storage-ring"><b>{Math.round(parseInt(d.used)/parseInt(d.capacity)*100)}%</b><span>UTILISÉ</span></div><dl><div><dt>CAPACITÉ</dt><dd>{d.capacity}</dd></div><div><dt>UTILISÉ</dt><dd>{d.used}</dd></div><div><dt>FIRMWARE</dt><dd>{d.firmware}</dd></div><div><dt>CONNEXION</dt><dd>USB · LOCAL</dd></div></dl><span className="integrity">✓ INTÉGRITÉ MACHINE OK</span></aside><section className="backup-work"><header><span><small>01 / CONTENU</small><h2>Éléments à sauvegarder</h2></span><button onClick={()=>setSelected(selected.length===d.folders.length?[]:d.folders.map(x=>x[0]))}>{selected.length===d.folders.length?"TOUT DÉCOCHER":"TOUT COCHER"}</button></header><div className="backup-folder-grid">{d.folders.map(([name,meta])=><button key={name} className={selected.includes(name)?"active":""} onClick={()=>toggle(name)}><i>{selected.includes(name)?"✓":""}</i><span><b>{name}</b><small>{meta}</small></span><strong>▰</strong></button>)}</div><div className="snapshot-action"><div><small>DESTINATION</small><b>/ENGINEERING_STUDIO/VAULT/{machine.toUpperCase()}/</b><span>{selected.length} CATÉGORIE{selected.length>1?"S":""} · SHA-256 · MANIFESTE JSON</span></div><button disabled={!selected.length} onClick={()=>setMessage(`SNAPSHOT CRÉÉ · ${selected.length} CATÉGORIE${selected.length>1?"S":""}`)}>CRÉER LE SNAPSHOT <b>→</b></button></div><output>{message}</output></section></section><section className="snapshot-history"><header><small>02 / HISTORIQUE</small><h2>Copies disponibles</h2></header><div className="snapshot-table"><div><b>DATE</b><b>CONTENU</b><b>TAILLE</b><b>ÉTAT</b><b>ACTION</b></div>{d.snapshots.map((s,i)=><div key={s[0]}><span>{s[0]}</span><span>{s[1]}</span><span>{s[2]}</span><strong>✓ {s[3]}</strong><button onClick={()=>setMessage(`RESTAURATION SÉLECTIONNÉE · ${s[0]}`)}>RESTAURER</button></div>)}</div></section></main>}
