import StudioHeader from "../../StudioHeader";
import "./vault.css";

const machines=[
 {id:"op-1",name:"OP-1",label:"SYNTHÉTISEUR · TAPE",image:"/media/teenage-engineering-op-1-pixel-art-music-workstation.jpeg",accent:"blue",state:"CONNECTÉ · USB",capacity:"256 MB",last:"17 AOÛT · 11:42",items:["4 PISTES TAPE","ALBUM A / B","DRUM & SYNTH","FIRMWARE 243"],info:["18 snapshots","SHA-256 vérifié","Restauration sélective"]},
 {id:"ep-133",name:"EP-133 K.O. II",label:"SAMPLER · COMPOSER",image:"/media/teenage-engineering-ep-133-ko-ii-pixel-art-sampler.jpeg",accent:"orange",state:"PRÊT · USB",capacity:"64 MB",last:"16 AOÛT · 22:18",items:["PROJETS","GROUPES A–D","PATTERNS & SCÈNES","SONS & RÉGLAGES"],info:["12 snapshots","Manifeste présent","Clone de projet"]}
];

export default function BackupHub(){return <main className="vault-page"><StudioHeader/><header className="vault-hero"><div><a href="/outils">← RETOUR AUX OUTILS</a><span>VAULT-01 · SAUVEGARDE LOCALE</span><h1>Choisir une<br/><em>machine.</em></h1><p>Deux coffres séparés. Des copies lisibles, vérifiées et restaurables sans magie nuageuse.</p></div><div className="vault-overview"><span><small>SNAPSHOTS</small><b>30</b></span><span><small>INTÉGRITÉ</small><b>100%</b></span><span><small>ESPACE</small><b>1.4 GB</b></span><strong>● COFFRE LOCAL DISPONIBLE</strong></div></header><section className="vault-machine-grid">{machines.map(m=><a key={m.id} href={`/outils/sauvegardes/${m.id}`} className={`vault-machine ${m.accent}`}><div className="vault-machine-visual"><img src={m.image} alt={`${m.name} en pixel art`}/><span>{m.state}</span></div><div className="vault-machine-copy"><small>{m.label}</small><h2>{m.name}</h2><div className="vault-facts"><span><small>CAPACITÉ MACHINE</small><b>{m.capacity}</b></span><span><small>DERNIÈRE COPIE</small><b>{m.last}</b></span></div><ul>{m.items.map(x=><li key={x}>✓ {x}</li>)}</ul><div className="vault-health">{m.info.map(x=><span key={x}>{x}</span>)}</div><strong className="vault-open">OUVRIR LES SAUVEGARDES <b>→</b></strong></div></a>)}</section></main>}
