"use client";
import {useEffect,useRef,useState} from "react";
import StudioHeader from "../../StudioHeader";
import "./editor.css";

type Tool="pencil"|"eraser"|"fill"|"line"|"rect"|"circle"|"picker"|"select";
const tools:[Tool,string,string][]=[["select","▧","Sélection"],["pencil","✎","Crayon 1 px"],["eraser","□","Gomme"],["fill","▣","Pot de peinture"],["line","╱","Ligne"],["rect","▭","Rectangle"],["circle","○","Ellipse"],["picker","⌁","Pipette"]];
const colors=["#000000","#ffffff","#ff3b18","#ffb000","#00a7d8","#00d36f","#9a63ff","#777b76"];
const assets=["BOOT_LOGO","TAPE_REEL","SYNTH_CLUSTER","DRUM_GRID","USB_SCREEN","RADIO_FX","CWO_WAVE","ENDLESS_SEQ"];

export default function Op1ImageEditor(){
 const canvas=useRef<HTMLCanvasElement>(null);const fileInput=useRef<HTMLInputElement>(null);const start=useRef<{x:number;y:number;data:ImageData}|null>(null);
 const [tool,setTool]=useState<Tool>("pencil");const [color,setColor]=useState("#ff3b18");const [zoom,setZoom]=useState(3);const [drawing,setDrawing]=useState(false);const [pos,setPos]=useState({x:0,y:0});const [library,setLibrary]=useState(true);const [menu,setMenu]=useState(false);const [grid,setGrid]=useState(true);const [name,setName]=useState("BOOT_LOGO");const [history,setHistory]=useState<ImageData[]>([]);
 useEffect(()=>{const c=canvas.current!,x=c.getContext("2d")!;x.imageSmoothingEnabled=false;x.fillStyle="#101210";x.fillRect(0,0,320,160);x.fillStyle="#e6e4df";x.fillRect(18,18,284,24);x.fillStyle="#ff3b18";x.fillRect(18,54,170,12);x.fillStyle="#ffb000";x.fillRect(18,76,250,5);x.fillStyle="#00a7d8";for(let i=0;i<10;i++)x.fillRect(20+i*27,105,17,28)},[]);
 function xy(e:React.PointerEvent<HTMLCanvasElement>){const r=e.currentTarget.getBoundingClientRect();return{x:Math.max(0,Math.min(319,Math.floor((e.clientX-r.left)*320/r.width))),y:Math.max(0,Math.min(159,Math.floor((e.clientY-r.top)*160/r.height)))}}
 function snapshot(){const x=canvas.current!.getContext("2d")!;setHistory(h=>[...h.slice(-19),x.getImageData(0,0,320,160)])}
 function dot(xp:number,yp:number){const x=canvas.current!.getContext("2d")!;if(tool==="picker"){const d=x.getImageData(xp,yp,1,1).data;setColor(`#${[d[0],d[1],d[2]].map(v=>v.toString(16).padStart(2,"0")).join("")}`);setTool("pencil");return}if(tool==="fill"){x.fillStyle=color;x.fillRect(0,0,320,160);return}if(tool==="pencil"){x.fillStyle=color;x.fillRect(xp,yp,1,1)}if(tool==="eraser")x.clearRect(xp,yp,1,1)}
 function down(e:React.PointerEvent<HTMLCanvasElement>){e.currentTarget.setPointerCapture(e.pointerId);const p=xy(e);snapshot();const x=canvas.current!.getContext("2d")!;start.current={...p,data:x.getImageData(0,0,320,160)};setDrawing(true);dot(p.x,p.y)}
 function move(e:React.PointerEvent<HTMLCanvasElement>){const p=xy(e);setPos(p);if(drawing&&(tool==="pencil"||tool==="eraser"))dot(p.x,p.y)}
 function up(e:React.PointerEvent<HTMLCanvasElement>){if(!drawing||!start.current)return;const p=xy(e),s=start.current,x=canvas.current!.getContext("2d")!;if(["line","rect","circle"].includes(tool)){x.putImageData(s.data,0,0);x.strokeStyle=color;x.lineWidth=1;x.beginPath();if(tool==="line"){x.moveTo(s.x+.5,s.y+.5);x.lineTo(p.x+.5,p.y+.5)}if(tool==="rect")x.rect(s.x+.5,s.y+.5,p.x-s.x,p.y-s.y);if(tool==="circle")x.ellipse((s.x+p.x)/2,(s.y+p.y)/2,Math.abs(p.x-s.x)/2,Math.abs(p.y-s.y)/2,0,0,Math.PI*2);x.stroke()}setDrawing(false);start.current=null}
 function undo(){const last=history.at(-1);if(!last)return;canvas.current!.getContext("2d")!.putImageData(last,0,0);setHistory(h=>h.slice(0,-1))}
 function clear(){snapshot();canvas.current!.getContext("2d")!.clearRect(0,0,320,160)}
 function exportPng(){const a=document.createElement("a");a.download=`${name}.png`;a.href=canvas.current!.toDataURL("image/png");a.click()}
 function importPng(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const img=new Image();img.onload=()=>{snapshot();const x=canvas.current!.getContext("2d")!;x.clearRect(0,0,320,160);x.imageSmoothingEnabled=false;x.drawImage(img,0,0,320,160)};img.src=URL.createObjectURL(f)}
 function loadAsset(asset:string,index:number){setName(asset);snapshot();const x=canvas.current!.getContext("2d")!;x.clearRect(0,0,320,160);x.fillStyle="#101210";x.fillRect(0,0,320,160);x.fillStyle=colors[index%colors.length];for(let i=0;i<12;i++)x.fillRect(12+i*25,(i*13+index*9)%120+15,14,(i%4+1)*6)}
 return <main className="draw-app"><StudioHeader/><div className="draw-menu"><div><button onClick={()=>setMenu(v=>!v)}>FICHIER</button>{menu&&<div className="file-pop"><button onClick={clear}>Nouveau</button><button onClick={()=>fileInput.current?.click()}>Ouvrir / importer…</button><button onClick={exportPng}>Enregistrer PNG</button><i/><button onClick={exportPng}>Exporter pour OP-1</button></div>}</div><button>ÉDITION</button><button>AFFICHAGE</button><button>OUTILS</button><button>PIXELS</button><button>CALQUES</button><button>AIDE</button><span/><b>OP-1 DISPLAY EDITOR · 320 × 160</b></div><div className="icon-toolbar"><button onClick={clear}>▱<small>NOUVEAU</small></button><button onClick={()=>fileInput.current?.click()}>▰<small>OUVRIR</small></button><button onClick={exportPng}>▣<small>SAUVER</small></button><i/><button onClick={undo}>↶<small>ANNULER</small></button><button disabled>↷<small>RÉTABLIR</small></button><i/><button className={grid?"active":""} onClick={()=>setGrid(v=>!v)}>▦<small>GRILLE</small></button><div className="zoom-buttons"><button onClick={()=>setZoom(z=>Math.max(1,z-1))} disabled={zoom===1}>−</button><button onClick={()=>setZoom(1)}>100%</button><button onClick={()=>setZoom(2)}>AJUSTER</button><button onClick={()=>setZoom(z=>Math.min(5,z+1))} disabled={zoom===5}>+</button><b>{zoom*100}%</b></div><span/><strong>ÉCRAN OP-1 <b>320×160</b></strong></div><input ref={fileInput} hidden type="file" accept="image/png,image/jpeg" onChange={importPng}/>
  <div className={`draw-layout ${library?"with-library":"no-library"}`}>
   {library?<aside className="image-library"><header><div><small>OP-1 ORIGINAL</small><b>IMAGES MACHINE</b></div><button onClick={()=>setLibrary(false)}>‹</button></header><div className="library-filter"><input placeholder="Rechercher…"/><button>⌕</button></div><nav><button className="active">TOUT</button><button>BOOT</button><button>TAPE</button><button>SYNTH</button></nav><div className="library-list">{assets.map((a,i)=><button key={a} className={name===a?"active":""} onClick={()=>loadAsset(a,i)}><div className={`factory-preview p${i}`}/><span><small>{i<2?"SYSTEM":i<4?"TAPE":"ENGINE"}</small><b>{a}</b><em>320×160</em></span></button>)}</div><footer><button onClick={()=>fileInput.current?.click()}>+ IMPORTER UNE IMAGE</button></footer></aside>:<button className="library-rail" onClick={()=>setLibrary(true)}>BIBLIOTHÈQUE <b>›</b></button>}
   <aside className="vertical-tools"><header>PALETTE <button>−</button></header><div className="left-swatches">{["#000000","#ffffff","#5b4037","#c48770","#822e32","#ff3b18","#ed8b32","#ffb000","#386a45","#00d36f","#266e78","#00a7d8","#324f83","#9a63ff","#76455e","#d55f96","#777b76","#b7bab4","#e6e4df","#f5d7c8"].map(c=><button key={c} style={{background:c}} className={color===c?"active":""} onClick={()=>setColor(c)}/>)}</div><div className="color-preview"><span style={{background:color}}/><b>{color.toUpperCase()}</b></div><header>OUTILS <button>−</button></header><div className="left-tool-grid">{tools.map(([id,icon,label])=><button key={id} className={tool===id?"active":""} title={label} onClick={()=>setTool(id)}><b>{icon}</b><span>{label}</span></button>)}</div></aside>
   <section className="drawing-space"><div className="doc-bar"><button className="active"><i/> {name}.PNG <b>×</b></button><button>+</button><span>RGB · TRANSPARENCE · 320 × 160</span></div><div className="screen-reference"><img src="/media/teenage-engineering-op-1-pixel-art-music-workstation.jpeg" alt="OP-1 original"/><div><small>ÉCRAN CIBLE</small><b>OP-1 · 320 × 160 PX</b><span>Chaque point dessiné correspond à un pixel réel.</span></div><strong>2:1</strong></div><div className="canvas-workarea"><div className="ruler top"><span>0</span><span>80</span><span>160</span><span>240</span><span>320</span></div><div className="ruler side"><span>0</span><span>40</span><span>80</span><span>120</span><span>160</span></div><div className={`canvas-holder ${grid?"show-grid":""}`}><canvas ref={canvas} width="320" height="160" style={{width:320*zoom,height:160*zoom}} onPointerDown={down} onPointerMove={move} onPointerUp={up}/></div></div><div className="draw-status"><span>X:{pos.x} Y:{pos.y}</span><span>320 × 160 px</span><span><i style={{background:color}}/> {color}</span><label>ZOOM<input type="range" min="1" max="5" value={zoom} onChange={e=>setZoom(+e.target.value)}/><b>{zoom*100}%</b></label></div></section>
   <aside className="inspector"><div className="quick-history"><button>▱<span>NOUVEAU CALQUE</span></button><button>▰<span>GROUPE</span></button></div><section className="layers"><header>CALQUES <button>+</button></header><button className="active"><i/>▦<span><b>PIXELS</b><small>NORMAL · 100%</small></span><strong>◉</strong></button><button><i/>▧<span><b>GUIDES OP-1</b><small>NORMAL · 50%</small></span><strong>◉</strong></button><button><i/>▨<span><b>FOND</b><small>VERROUILLÉ</small></span><strong>◆</strong></button></section><section className="pixel-options"><header>PROPRIÉTÉS</header><label>LARGEUR <input value="320 px" readOnly/></label><label>HAUTEUR <input value="160 px" readOnly/></label><label>OPACITÉ <input type="range" value="100" readOnly/> 100%</label></section><button className="export-op1" onClick={exportPng}>EXPORTER POUR OP-1 <span>→</span></button></aside>
  </div>
 </main>
}
