/**
 * gameSongsCatalog.ts — Banque complète de 40 Morceaux & Exercices d'apprentissage OP-1.
 * 
 * 4 Catégories distinctes · 10 Exercices par catégorie classés par Niveaux 1 à 10 :
 * 
 * 1. "melody" : Mélodies & Leads Modernes (Niveaux 1 à 10)
 *    - Niv. 1 : Pentatonique R&B / Lo-Fi
 *    - Niv. 2 : Synthwave 80s Neon Hook
 *    - Niv. 3 : Afrobeat Syncopated Guitar / Synth
 *    - Niv. 4 : Melodic Techno Pluck Sequence
 *    - Niv. 5 : UK Drill Melancholic Minor Piano
 *    - Niv. 6 : French Touch Filtered Disco Lead
 *    - Niv. 7 : Future Bass Supersaw Drop Riff
 *    - Niv. 8 : Hyperpop Glitch High-Speed Runs
 *    - Niv. 9 : Cyberpunk 2077 Heavy Bassline
 *    - Niv. 10 : Neo-Soul Jazz Sweeps & Riffs Virtuose
 * 
 * 2. "chord" : Accords & Harmonies Contemporaines (Niveaux 1 à 10)
 *    - Niv. 1 : Triades Fondamentales (C - F - G)
 *    - Niv. 2 : Pop Anthem I - V - vi - IV
 *    - Niv. 3 : Lo-Fi Jazzy 7th Keys (Am7 - Dm7 - Em7 - Fmaj7)
 *    - Niv. 4 : Dark Trap Minor Progression (Cm - Ab - Fm - G)
 *    - Niv. 5 : Nu-Disco Funky Stabs (Dm9 - Gm7 - C9 - Fmaj7)
 *    - Niv. 6 : Amapiano Deep Lush Chords (Ebm7 - Bbm7 - Abm7)
 *    - Niv. 7 : Neo-Soul 9th & 11th Voicings (Dmaj9 - C#m7 - Bm9 - A13)
 *    - Niv. 8 : Future Bass Sidechained 16th Grooves
 *    - Niv. 9 : Jazz Coltrane Giant Steps Modulations
 *    - Niv. 10 : Cinematic Gospel & Reharmonisation Avancée
 * 
 * 3. "drum" : Finger Drumming OP-1 (Mapping officiel 53-76) (Niveaux 1 à 10)
 *    - Niv. 1 : Initiation Pulse (Kick 53, Snare 55, Hat 57)
 *    - Niv. 2 : Boom Bap Hip-Hop 90s NYC Classic
 *    - Niv. 3 : French House & 909 4-on-the-Floor (Kick 53, Clap 56, OpenHat 59)
 *    - Niv. 4 : Lo-Fi Vinyl Dusty Beat & Scratch 73
 *    - Niv. 5 : Afrobeat Syncopated Shakers 65 & Congas 69/70
 *    - Niv. 6 : Amapiano Shaker Groove & Sub Log Drum 76
 *    - Niv. 7 : Modern Trap & 808 Rolls (Sub 54, Rim 56, Hat Roll 57, Vox 75)
 *    - Niv. 8 : UK Drill Sliding Hats & Ghost Snares
 *    - Niv. 9 : Jersey Club & Baile Funk Fast Triplets
 *    - Niv. 10 : Drum & Bass Jungle 168 BPM Amen Break Virtuose
 * 
 * 4. "arcade" : Arcade & Styles Modernes (Niveaux 1 à 10)
 *    - Niv. 1 : Gameboy Chiptune 8-Bit Nostalgia
 *    - Niv. 2 : Tetris Korobeiniki Russian Folk Riff
 *    - Niv. 3 : Outrun Retrowave Highway Chase
 *    - Niv. 4 : Tokyo Drift Drift Phonk Heavy Bass & Cowbell
 *    - Niv. 5 : Daft Punk French Touch One More Time Tribute
 *    - Niv. 6 : Cyberpunk Neon Boss Fight
 *    - Niv. 7 : Hyperpop Speedcore Glitch Anthem
 *    - Niv. 8 : Kawaii Future Bass Drop
 *    - Niv. 9 : EDM Festival Big Room Drop
 *    - Niv. 10 : Grand Maître Arcade Final Boss Rush
 */

export interface GameNote {
  note: number;            // MIDI Note number (ex: 53 = Kick, 60 = C4)
  startSeconds: number;    // Début en secondes
  durationSeconds: number; // Durée
  velocity?: number;
  label?: string;          // Nom lisible affiché sur la capsule
}

export interface GameSongTheme {
  id: string;
  title: string;
  category: "melody" | "chord" | "drum" | "arcade";
  level: number; // 1 à 10
  icon: string;
  bpm: number;
  difficulty: "Débutant" | "Débutant+" | "Intermédiaire" | "Intermédiaire+" | "Avancé" | "Avancé+" | "Pro" | "Pro+" | "Expert" | "Grand Maître";
  description: string;
  durationSeconds: number;
  recommendedEngine: string;
  recommendedPatch: string;
  notes: GameNote[];
}

export const GAME_SONG_THEMES: GameSongTheme[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // CATÉGORIE 1 : MÉLODIES & LEADS MODERNES (10 EXERCICES / NIVEAUX 1 À 10)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "melody_lvl1_pentatonic_rnb",
    title: "Gamme Pentatonique & Riff Lo-Fi R&B",
    category: "melody",
    level: 1,
    icon: "🎹",
    bpm: 85,
    difficulty: "Débutant",
    description: "Échauffement doux des doigts sur la gamme pentatonique majeure (C, D, E, G, A) avec phrasé R&B.",
    durationSeconds: 18.0,
    recommendedEngine: "FM",
    recommendedPatch: "Acid Sequence",
    notes: [
      { note: 60, startSeconds: 0.0, durationSeconds: 0.6, label: "C4" },
      { note: 62, startSeconds: 0.7, durationSeconds: 0.6, label: "D4" },
      { note: 64, startSeconds: 1.4, durationSeconds: 0.6, label: "E4" },
      { note: 67, startSeconds: 2.1, durationSeconds: 0.6, label: "G4" },
      { note: 69, startSeconds: 2.8, durationSeconds: 1.2, label: "A4" },
      // Descente
      { note: 69, startSeconds: 4.4, durationSeconds: 0.5, label: "A4" },
      { note: 67, startSeconds: 5.0, durationSeconds: 0.5, label: "G4" },
      { note: 64, startSeconds: 5.6, durationSeconds: 0.5, label: "E4" },
      { note: 62, startSeconds: 6.2, durationSeconds: 0.5, label: "D4" },
      { note: 60, startSeconds: 6.8, durationSeconds: 1.4, label: "C4" },
      // Motif R&B
      { note: 64, startSeconds: 8.8, durationSeconds: 0.4, label: "E4" },
      { note: 67, startSeconds: 9.3, durationSeconds: 0.4, label: "G4" },
      { note: 69, startSeconds: 9.8, durationSeconds: 0.6, label: "A4" },
      { note: 67, startSeconds: 10.6, durationSeconds: 0.4, label: "G4" },
      { note: 64, startSeconds: 11.1, durationSeconds: 0.8, label: "E4" },
      { note: 62, startSeconds: 12.2, durationSeconds: 0.4, label: "D4" },
      { note: 60, startSeconds: 12.8, durationSeconds: 0.5, label: "C4" },
      { note: 64, startSeconds: 13.5, durationSeconds: 0.5, label: "E4" },
      { note: 62, startSeconds: 14.2, durationSeconds: 0.6, label: "D4" },
      { note: 60, startSeconds: 15.0, durationSeconds: 2.2, label: "C4" },
    ],
  },
  {
    id: "melody_lvl2_synthwave_neon",
    title: "Synthwave 80s Neon Arp Hook",
    category: "melody",
    level: 2,
    icon: "🌆",
    bpm: 105,
    difficulty: "Débutant+",
    description: "Arpèges montants et descendants rétro-futuristes en croches régulières sur basse La mineur.",
    durationSeconds: 20.0,
    recommendedEngine: "Pulse",
    recommendedPatch: "Virtual Analog Saw Lead",
    notes: [
      { note: 57, startSeconds: 0.0, durationSeconds: 0.4, label: "A3" },
      { note: 60, startSeconds: 0.5, durationSeconds: 0.4, label: "C4" },
      { note: 64, startSeconds: 1.0, durationSeconds: 0.4, label: "E4" },
      { note: 69, startSeconds: 1.5, durationSeconds: 0.6, label: "A4" },
      { note: 67, startSeconds: 2.3, durationSeconds: 0.4, label: "G4" },
      { note: 64, startSeconds: 2.8, durationSeconds: 0.4, label: "E4" },
      { note: 60, startSeconds: 3.3, durationSeconds: 0.4, label: "C4" },
      { note: 62, startSeconds: 3.8, durationSeconds: 0.8, label: "D4" },
      // Cycle 2
      { note: 57, startSeconds: 5.0, durationSeconds: 0.4, label: "A3" },
      { note: 60, startSeconds: 5.5, durationSeconds: 0.4, label: "C4" },
      { note: 64, startSeconds: 6.0, durationSeconds: 0.4, label: "E4" },
      { note: 72, startSeconds: 6.5, durationSeconds: 0.6, label: "C5" },
      { note: 71, startSeconds: 7.3, durationSeconds: 0.4, label: "B4" },
      { note: 67, startSeconds: 7.8, durationSeconds: 0.4, label: "G4" },
      { note: 64, startSeconds: 8.3, durationSeconds: 0.4, label: "E4" },
      { note: 69, startSeconds: 8.8, durationSeconds: 1.2, label: "A4" },
      // Phrase 3
      { note: 65, startSeconds: 10.5, durationSeconds: 0.4, label: "F4" },
      { note: 69, startSeconds: 11.0, durationSeconds: 0.4, label: "A4" },
      { note: 72, startSeconds: 11.5, durationSeconds: 0.6, label: "C5" },
      { note: 67, startSeconds: 12.3, durationSeconds: 0.4, label: "G4" },
      { note: 71, startSeconds: 12.8, durationSeconds: 0.4, label: "B4" },
      { note: 74, startSeconds: 13.3, durationSeconds: 0.6, label: "D5" },
      { note: 69, startSeconds: 14.2, durationSeconds: 0.5, label: "A4" },
      { note: 64, startSeconds: 14.8, durationSeconds: 0.5, label: "E4" },
      { note: 60, startSeconds: 15.4, durationSeconds: 0.5, label: "C4" },
      { note: 57, startSeconds: 16.0, durationSeconds: 2.5, label: "A3" },
    ],
  },
  {
    id: "melody_lvl3_afrobeat_lead",
    title: "Afrobeat Syncopated Hook (Burna/Rema style)",
    category: "melody",
    level: 3,
    icon: "🌍",
    bpm: 108,
    difficulty: "Intermédiaire",
    description: "Mélodie dansante syncopée avec appoggiatures et décalages rythmiques typiques de Lagos.",
    durationSeconds: 22.0,
    recommendedEngine: "Cluster",
    recommendedPatch: "Tape Velvet Keys",
    notes: [
      { note: 64, startSeconds: 0.0, durationSeconds: 0.35, label: "E4" },
      { note: 67, startSeconds: 0.4, durationSeconds: 0.35, label: "G4" },
      { note: 69, startSeconds: 0.8, durationSeconds: 0.7, label: "A4" },
      { note: 67, startSeconds: 1.7, durationSeconds: 0.35, label: "G4" },
      { note: 64, startSeconds: 2.1, durationSeconds: 0.5, label: "E4" },
      { note: 62, startSeconds: 2.8, durationSeconds: 0.35, label: "D4" },
      { note: 64, startSeconds: 3.2, durationSeconds: 0.7, label: "E4" },
      // Répétition syncopée
      { note: 64, startSeconds: 4.3, durationSeconds: 0.35, label: "E4" },
      { note: 67, startSeconds: 4.7, durationSeconds: 0.35, label: "G4" },
      { note: 71, startSeconds: 5.1, durationSeconds: 0.35, label: "B4" },
      { note: 69, startSeconds: 5.6, durationSeconds: 0.8, label: "A4" },
      { note: 67, startSeconds: 6.6, durationSeconds: 0.35, label: "G4" },
      { note: 64, startSeconds: 7.0, durationSeconds: 0.35, label: "E4" },
      { note: 62, startSeconds: 7.4, durationSeconds: 0.35, label: "D4" },
      { note: 60, startSeconds: 7.9, durationSeconds: 1.2, label: "C4" },
      // Deuxième cycle avec variation
      { note: 60, startSeconds: 9.6, durationSeconds: 0.3, label: "C4" },
      { note: 62, startSeconds: 10.0, durationSeconds: 0.3, label: "D4" },
      { note: 64, startSeconds: 10.4, durationSeconds: 0.5, label: "E4" },
      { note: 67, startSeconds: 11.1, durationSeconds: 0.5, label: "G4" },
      { note: 69, startSeconds: 11.8, durationSeconds: 0.9, label: "A4" },
      { note: 72, startSeconds: 13.0, durationSeconds: 0.4, label: "C5" },
      { note: 69, startSeconds: 13.5, durationSeconds: 0.4, label: "A4" },
      { note: 67, startSeconds: 14.0, durationSeconds: 0.4, label: "G4" },
      { note: 64, startSeconds: 14.5, durationSeconds: 0.6, label: "E4" },
      { note: 62, startSeconds: 15.3, durationSeconds: 0.4, label: "D4" },
      { note: 60, startSeconds: 15.9, durationSeconds: 2.0, label: "C4" },
    ],
  },
  {
    id: "melody_lvl4_melodic_techno",
    title: "Melodic Techno Pluck Sequence",
    category: "melody",
    level: 4,
    icon: "🔊",
    bpm: 124,
    difficulty: "Intermédiaire+",
    description: "Séquence hypnotique en doubles-croches continues style Afterlife / Tale of Us.",
    durationSeconds: 22.0,
    recommendedEngine: "FM",
    recommendedPatch: "Acid Sequence",
    notes: [
      { note: 57, startSeconds: 0.0, durationSeconds: 0.18, label: "A3" },
      { note: 60, startSeconds: 0.24, durationSeconds: 0.18, label: "C4" },
      { note: 64, startSeconds: 0.48, durationSeconds: 0.18, label: "E4" },
      { note: 67, startSeconds: 0.72, durationSeconds: 0.18, label: "G4" },
      { note: 64, startSeconds: 0.96, durationSeconds: 0.18, label: "E4" },
      { note: 60, startSeconds: 1.2, durationSeconds: 0.18, label: "C4" },
      { note: 57, startSeconds: 1.44, durationSeconds: 0.18, label: "A3" },
      { note: 62, startSeconds: 1.68, durationSeconds: 0.18, label: "D4" },
      { note: 57, startSeconds: 1.92, durationSeconds: 0.18, label: "A3" },
      { note: 60, startSeconds: 2.16, durationSeconds: 0.18, label: "C4" },
      { note: 64, startSeconds: 2.4, durationSeconds: 0.18, label: "E4" },
      { note: 69, startSeconds: 2.64, durationSeconds: 0.18, label: "A4" },
      { note: 67, startSeconds: 2.88, durationSeconds: 0.18, label: "G4" },
      { note: 64, startSeconds: 3.12, durationSeconds: 0.18, label: "E4" },
      { note: 62, startSeconds: 3.36, durationSeconds: 0.18, label: "D4" },
      { note: 60, startSeconds: 3.6, durationSeconds: 0.35, label: "C4" },
      // Répétition dynamique
      { note: 57, startSeconds: 4.2, durationSeconds: 0.18, label: "A3" },
      { note: 60, startSeconds: 4.44, durationSeconds: 0.18, label: "C4" },
      { note: 64, startSeconds: 4.68, durationSeconds: 0.18, label: "E4" },
      { note: 72, startSeconds: 4.92, durationSeconds: 0.22, label: "C5" },
      { note: 71, startSeconds: 5.16, durationSeconds: 0.18, label: "B4" },
      { note: 67, startSeconds: 5.4, durationSeconds: 0.18, label: "G4" },
      { note: 69, startSeconds: 5.64, durationSeconds: 0.5, label: "A4" },
      { note: 64, startSeconds: 6.3, durationSeconds: 0.18, label: "E4" },
      { note: 60, startSeconds: 6.54, durationSeconds: 0.18, label: "C4" },
      { note: 57, startSeconds: 6.78, durationSeconds: 1.8, label: "A3" },
    ],
  },
  {
    id: "melody_lvl5_drill_piano",
    title: "UK Drill Melancholic Minor Piano",
    category: "melody",
    level: 5,
    icon: "🗡️",
    bpm: 142,
    difficulty: "Avancé",
    description: "Ligne de piano sombre et agressive avec trilles aiguës et staccatos précis (Central Cee style).",
    durationSeconds: 24.0,
    recommendedEngine: "Cluster",
    recommendedPatch: "Tape Velvet Keys",
    notes: [
      { note: 60, startSeconds: 0.0, durationSeconds: 0.3, label: "C4" },
      { note: 63, startSeconds: 0.35, durationSeconds: 0.3, label: "Eb4" },
      { note: 67, startSeconds: 0.7, durationSeconds: 0.6, label: "G4" },
      { note: 70, startSeconds: 1.5, durationSeconds: 0.3, label: "Bb4" },
      { note: 68, startSeconds: 1.9, durationSeconds: 0.3, label: "Ab4" },
      { note: 67, startSeconds: 2.3, durationSeconds: 0.8, label: "G4" },
      // Riff aigu rapide
      { note: 72, startSeconds: 3.4, durationSeconds: 0.2, label: "C5" },
      { note: 75, startSeconds: 3.65, durationSeconds: 0.2, label: "Eb5" },
      { note: 74, startSeconds: 3.9, durationSeconds: 0.2, label: "D5" },
      { note: 72, startSeconds: 4.15, durationSeconds: 0.5, label: "C5" },
      { note: 70, startSeconds: 4.8, durationSeconds: 0.3, label: "Bb4" },
      { note: 67, startSeconds: 5.2, durationSeconds: 1.2, label: "G4" },
      // Phrase 2
      { note: 58, startSeconds: 6.8, durationSeconds: 0.3, label: "Bb3" },
      { note: 61, startSeconds: 7.15, durationSeconds: 0.3, label: "Db4" },
      { note: 65, startSeconds: 7.5, durationSeconds: 0.6, label: "F4" },
      { note: 68, startSeconds: 8.3, durationSeconds: 0.3, label: "Ab4" },
      { note: 67, startSeconds: 8.7, durationSeconds: 0.3, label: "G4" },
      { note: 63, startSeconds: 9.1, durationSeconds: 0.8, label: "Eb4" },
      { note: 60, startSeconds: 10.2, durationSeconds: 2.2, label: "C4" },
    ],
  },
  {
    id: "melody_lvl6_french_touch_lead",
    title: "French Touch Filtered Disco Funky Lead",
    category: "melody",
    level: 6,
    icon: "🪩",
    bpm: 125,
    difficulty: "Avancé+",
    description: "Le son signature parisien : groove disco électrisant avec montées d'octave et glissés à la Justice / Cassius.",
    durationSeconds: 24.0,
    recommendedEngine: "Pulse",
    recommendedPatch: "Virtual Analog Saw Lead",
    notes: [
      { note: 60, startSeconds: 0.0, durationSeconds: 0.2, label: "C4" },
      { note: 60, startSeconds: 0.24, durationSeconds: 0.2, label: "C4" },
      { note: 64, startSeconds: 0.48, durationSeconds: 0.3, label: "E4" },
      { note: 67, startSeconds: 0.96, durationSeconds: 0.4, label: "G4" },
      { note: 69, startSeconds: 1.44, durationSeconds: 0.25, label: "A4" },
      { note: 72, startSeconds: 1.8, durationSeconds: 0.6, label: "C5" },
      { note: 71, startSeconds: 2.5, durationSeconds: 0.2, label: "B4" },
      { note: 69, startSeconds: 2.75, durationSeconds: 0.2, label: "A4" },
      { note: 67, startSeconds: 3.0, durationSeconds: 0.35, label: "G4" },
      { note: 64, startSeconds: 3.5, durationSeconds: 0.6, label: "E4" },
      // Riff funky
      { note: 62, startSeconds: 4.4, durationSeconds: 0.2, label: "D4" },
      { note: 64, startSeconds: 4.65, durationSeconds: 0.2, label: "E4" },
      { note: 65, startSeconds: 4.9, durationSeconds: 0.3, label: "F4" },
      { note: 69, startSeconds: 5.3, durationSeconds: 0.5, label: "A4" },
      { note: 67, startSeconds: 6.0, durationSeconds: 0.3, label: "G4" },
      { note: 64, startSeconds: 6.4, durationSeconds: 0.3, label: "E4" },
      { note: 62, startSeconds: 6.8, durationSeconds: 0.3, label: "D4" },
      { note: 60, startSeconds: 7.2, durationSeconds: 1.8, label: "C4" },
    ],
  },
  {
    id: "melody_lvl7_future_bass_lead",
    title: "Future Bass Supersaw Lead Drop",
    category: "melody",
    level: 7,
    icon: "⚡",
    bpm: 150,
    difficulty: "Pro",
    description: "Sauts de quartes et quintes ultra dynamiques à haute vélocité façon Flume / Illenium.",
    durationSeconds: 26.0,
    recommendedEngine: "FM",
    recommendedPatch: "Dream Poly Synth",
    notes: [
      { note: 65, startSeconds: 0.0, durationSeconds: 0.18, label: "F4" },
      { note: 69, startSeconds: 0.2, durationSeconds: 0.18, label: "A4" },
      { note: 72, startSeconds: 0.4, durationSeconds: 0.3, label: "C5" },
      { note: 76, startSeconds: 0.8, durationSeconds: 0.45, label: "E5" },
      { note: 74, startSeconds: 1.4, durationSeconds: 0.2, label: "D5" },
      { note: 72, startSeconds: 1.65, durationSeconds: 0.2, label: "C5" },
      { note: 69, startSeconds: 1.9, durationSeconds: 0.4, label: "A4" },
      { note: 67, startSeconds: 2.4, durationSeconds: 0.6, label: "G4" },
      // Drop run
      { note: 60, startSeconds: 3.2, durationSeconds: 0.15, label: "C4" },
      { note: 64, startSeconds: 3.4, durationSeconds: 0.15, label: "E4" },
      { note: 67, startSeconds: 3.6, durationSeconds: 0.15, label: "G4" },
      { note: 71, startSeconds: 3.8, durationSeconds: 0.15, label: "B4" },
      { note: 74, startSeconds: 4.0, durationSeconds: 0.3, label: "D5" },
      { note: 72, startSeconds: 4.4, durationSeconds: 0.6, label: "C5" },
      { note: 69, startSeconds: 5.2, durationSeconds: 0.2, label: "A4" },
      { note: 65, startSeconds: 5.5, durationSeconds: 0.4, label: "F4" },
      { note: 60, startSeconds: 6.1, durationSeconds: 1.5, label: "C4" },
    ],
  },
  {
    id: "melody_lvl8_hyperpop_glitch",
    title: "Hyperpop Glitch High-Speed Runs",
    category: "melody",
    level: 8,
    icon: "🍭",
    bpm: 160,
    difficulty: "Pro+",
    description: "Vitesse folle, staccatos agressifs et sauts d'octave ultra stimulants (Charli XCX / 100 gecs).",
    durationSeconds: 26.0,
    recommendedEngine: "Pulse",
    recommendedPatch: "Acid Bassline 303",
    notes: [
      { note: 60, startSeconds: 0.0, durationSeconds: 0.12, label: "C4" },
      { note: 60, startSeconds: 0.15, durationSeconds: 0.12, label: "C4" },
      { note: 72, startSeconds: 0.3, durationSeconds: 0.15, label: "C5" },
      { note: 71, startSeconds: 0.5, durationSeconds: 0.12, label: "B4" },
      { note: 69, startSeconds: 0.65, durationSeconds: 0.12, label: "A4" },
      { note: 67, startSeconds: 0.8, durationSeconds: 0.2, label: "G4" },
      { note: 65, startSeconds: 1.1, durationSeconds: 0.12, label: "F4" },
      { note: 64, startSeconds: 1.25, durationSeconds: 0.12, label: "E4" },
      { note: 62, startSeconds: 1.4, durationSeconds: 0.2, label: "D4" },
      { note: 60, startSeconds: 1.7, durationSeconds: 0.35, label: "C4" },
      // Rafale
      { note: 67, startSeconds: 2.2, durationSeconds: 0.1, label: "G4" },
      { note: 69, startSeconds: 2.32, durationSeconds: 0.1, label: "A4" },
      { note: 71, startSeconds: 2.44, durationSeconds: 0.1, label: "B4" },
      { note: 72, startSeconds: 2.56, durationSeconds: 0.25, label: "C5" },
      { note: 74, startSeconds: 2.9, durationSeconds: 0.12, label: "D5" },
      { note: 76, startSeconds: 3.1, durationSeconds: 0.4, label: "E5" },
      { note: 72, startSeconds: 3.6, durationSeconds: 0.15, label: "C5" },
      { note: 67, startSeconds: 3.85, durationSeconds: 0.15, label: "G4" },
      { note: 60, startSeconds: 4.1, durationSeconds: 1.2, label: "C4" },
    ],
  },
  {
    id: "melody_lvl9_cyberpunk_bassline",
    title: "Cyberpunk 2077 Heavy Synth Bassline",
    category: "melody",
    level: 9,
    icon: "🤖",
    bpm: 132,
    difficulty: "Expert",
    description: "Basse électro industrielle saturée et distordue avec glissés de demi-tons et chromatismes.",
    durationSeconds: 28.0,
    recommendedEngine: "Voltage",
    recommendedPatch: "Acid Bassline 303",
    notes: [
      { note: 53, startSeconds: 0.0, durationSeconds: 0.2, label: "F3" },
      { note: 53, startSeconds: 0.22, durationSeconds: 0.2, label: "F3" },
      { note: 54, startSeconds: 0.45, durationSeconds: 0.2, label: "F#3" },
      { note: 53, startSeconds: 0.7, durationSeconds: 0.25, label: "F3" },
      { note: 56, startSeconds: 1.1, durationSeconds: 0.3, label: "G#3" },
      { note: 55, startSeconds: 1.5, durationSeconds: 0.2, label: "G3" },
      { note: 53, startSeconds: 1.8, durationSeconds: 0.4, label: "F3" },
      // Run chromatique
      { note: 52, startSeconds: 2.4, durationSeconds: 0.15, label: "E3" },
      { note: 53, startSeconds: 2.58, durationSeconds: 0.15, label: "F3" },
      { note: 54, startSeconds: 2.76, durationSeconds: 0.15, label: "F#3" },
      { note: 55, startSeconds: 2.94, durationSeconds: 0.3, label: "G3" },
      { note: 53, startSeconds: 3.4, durationSeconds: 0.5, label: "F3" },
      { note: 60, startSeconds: 4.1, durationSeconds: 0.3, label: "C4" },
      { note: 58, startSeconds: 4.5, durationSeconds: 0.3, label: "Bb3" },
      { note: 53, startSeconds: 5.0, durationSeconds: 1.8, label: "F3" },
    ],
  },
  {
    id: "melody_lvl10_neosoul_virtuoso",
    title: "Neo-Soul Jazz Sweeps & Runs Virtuose",
    category: "melody",
    level: 10,
    icon: "👑",
    bpm: 94,
    difficulty: "Grand Maître",
    description: "Le sommet technique : descentes jazz Bebop, tierces rapides, substitutions tritoniques et sweep fluide.",
    durationSeconds: 32.0,
    recommendedEngine: "FM",
    recommendedPatch: "Dream Poly Synth",
    notes: [
      { note: 60, startSeconds: 0.0, durationSeconds: 0.15, label: "C4" },
      { note: 62, startSeconds: 0.16, durationSeconds: 0.15, label: "D4" },
      { note: 64, startSeconds: 0.32, durationSeconds: 0.15, label: "E4" },
      { note: 67, startSeconds: 0.48, durationSeconds: 0.2, label: "G4" },
      { note: 69, startSeconds: 0.72, durationSeconds: 0.15, label: "A4" },
      { note: 71, startSeconds: 0.88, durationSeconds: 0.15, label: "B4" },
      { note: 72, startSeconds: 1.04, durationSeconds: 0.25, label: "C5" },
      { note: 74, startSeconds: 1.35, durationSeconds: 0.15, label: "D5" },
      { note: 76, startSeconds: 1.52, durationSeconds: 0.4, label: "E5" },
      // Descente Bebop chromatique
      { note: 75, startSeconds: 2.1, durationSeconds: 0.12, label: "Eb5" },
      { note: 74, startSeconds: 2.24, durationSeconds: 0.12, label: "D5" },
      { note: 73, startSeconds: 2.38, durationSeconds: 0.12, label: "Db5" },
      { note: 72, startSeconds: 2.52, durationSeconds: 0.2, label: "C5" },
      { note: 69, startSeconds: 2.8, durationSeconds: 0.15, label: "A4" },
      { note: 67, startSeconds: 3.0, durationSeconds: 0.15, label: "G4" },
      { note: 65, startSeconds: 3.2, durationSeconds: 0.15, label: "F4" },
      { note: 64, startSeconds: 3.4, durationSeconds: 0.3, label: "E4" },
      { note: 62, startSeconds: 3.8, durationSeconds: 0.15, label: "D4" },
      { note: 60, startSeconds: 4.0, durationSeconds: 0.5, label: "C4" },
      { note: 57, startSeconds: 4.7, durationSeconds: 2.5, label: "A3" },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // CATÉGORIE 2 : ACCORDS & HARMONIES (10 EXERCICES / NIVEAUX 1 À 10)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "chord_lvl1_triads_fundation",
    title: "Triades Fondamentales (C – F – G)",
    category: "chord",
    level: 1,
    icon: "🎹",
    bpm: 80,
    difficulty: "Débutant",
    description: "Apprentissage des triades majeures de base à 3 notes plaquées sur le clavier.",
    durationSeconds: 18.0,
    recommendedEngine: "Cluster",
    recommendedPatch: "Tape Velvet Keys",
    notes: [
      // C Majeur (60, 64, 67)
      { note: 60, startSeconds: 0.0, durationSeconds: 2.5, label: "C (60)" },
      { note: 64, startSeconds: 0.0, durationSeconds: 2.5, label: "E (64)" },
      { note: 67, startSeconds: 0.0, durationSeconds: 2.5, label: "G (67)" },
      // F Majeur (53, 57, 60)
      { note: 53, startSeconds: 3.0, durationSeconds: 2.5, label: "F (53)" },
      { note: 57, startSeconds: 3.0, durationSeconds: 2.5, label: "A (57)" },
      { note: 60, startSeconds: 3.0, durationSeconds: 2.5, label: "C (60)" },
      // G Majeur (55, 59, 62)
      { note: 55, startSeconds: 6.0, durationSeconds: 2.5, label: "G (55)" },
      { note: 59, startSeconds: 6.0, durationSeconds: 2.5, label: "B (59)" },
      { note: 62, startSeconds: 6.0, durationSeconds: 2.5, label: "D (62)" },
      // Résolution C Majeur
      { note: 60, startSeconds: 9.0, durationSeconds: 3.5, label: "C (60)" },
      { note: 64, startSeconds: 9.0, durationSeconds: 3.5, label: "E (64)" },
      { note: 67, startSeconds: 9.0, durationSeconds: 3.5, label: "G (67)" },
    ],
  },
  {
    id: "chord_lvl2_pop_anthem",
    title: "Pop Anthem (I – V – vi – IV)",
    category: "chord",
    level: 2,
    icon: "🌟",
    bpm: 88,
    difficulty: "Débutant+",
    description: "La progression de hits la plus célèbre : Do Majeur · Sol Majeur · La Mineur · Fa Majeur.",
    durationSeconds: 22.0,
    recommendedEngine: "Cluster",
    recommendedPatch: "Tape Velvet Keys",
    notes: [
      // C (60, 64, 67)
      { note: 60, startSeconds: 0.0, durationSeconds: 2.2, label: "C Maj" },
      { note: 64, startSeconds: 0.0, durationSeconds: 2.2, label: "C Maj" },
      { note: 67, startSeconds: 0.0, durationSeconds: 2.2, label: "C Maj" },
      // G (55, 59, 62)
      { note: 55, startSeconds: 2.6, durationSeconds: 2.2, label: "G Maj" },
      { note: 59, startSeconds: 2.6, durationSeconds: 2.2, label: "G Maj" },
      { note: 62, startSeconds: 2.6, durationSeconds: 2.2, label: "G Maj" },
      // Am (57, 60, 64)
      { note: 57, startSeconds: 5.2, durationSeconds: 2.2, label: "A Min" },
      { note: 60, startSeconds: 5.2, durationSeconds: 2.2, label: "A Min" },
      { note: 64, startSeconds: 5.2, durationSeconds: 2.2, label: "A Min" },
      // F (53, 57, 60)
      { note: 53, startSeconds: 7.8, durationSeconds: 2.2, label: "F Maj" },
      { note: 57, startSeconds: 7.8, durationSeconds: 2.2, label: "F Maj" },
      { note: 60, startSeconds: 7.8, durationSeconds: 2.2, label: "F Maj" },
    ],
  },
  {
    id: "chord_lvl3_lofi_jazzy_keys",
    title: "Lo-Fi Jazzy 7th Keys (Am7 – Dm7 – Em7 – Fmaj7)",
    category: "chord",
    level: 3,
    icon: "☕",
    bpm: 82,
    difficulty: "Intermédiaire",
    description: "Accords de septièmes chaleureux et relaxants pour beats Lo-Fi d'étude.",
    durationSeconds: 24.0,
    recommendedEngine: "Cluster",
    recommendedPatch: "Tape Velvet Keys",
    notes: [
      // Am7 (57, 60, 64, 67)
      { note: 57, startSeconds: 0.0, durationSeconds: 2.4, label: "Am7" },
      { note: 60, startSeconds: 0.0, durationSeconds: 2.4, label: "Am7" },
      { note: 64, startSeconds: 0.0, durationSeconds: 2.4, label: "Am7" },
      { note: 67, startSeconds: 0.0, durationSeconds: 2.4, label: "Am7" },
      // Dm7 (62, 65, 69, 72)
      { note: 62, startSeconds: 2.8, durationSeconds: 2.4, label: "Dm7" },
      { note: 65, startSeconds: 2.8, durationSeconds: 2.4, label: "Dm7" },
      { note: 69, startSeconds: 2.8, durationSeconds: 2.4, label: "Dm7" },
      { note: 72, startSeconds: 2.8, durationSeconds: 2.4, label: "Dm7" },
      // Em7 (64, 67, 71, 74)
      { note: 64, startSeconds: 5.6, durationSeconds: 2.4, label: "Em7" },
      { note: 67, startSeconds: 5.6, durationSeconds: 2.4, label: "Em7" },
      { note: 71, startSeconds: 5.6, durationSeconds: 2.4, label: "Em7" },
      { note: 74, startSeconds: 5.6, durationSeconds: 2.4, label: "Em7" },
      // Fmaj7 (53, 57, 60, 64)
      { note: 53, startSeconds: 8.4, durationSeconds: 3.0, label: "Fmaj7" },
      { note: 57, startSeconds: 8.4, durationSeconds: 3.0, label: "Fmaj7" },
      { note: 60, startSeconds: 8.4, durationSeconds: 3.0, label: "Fmaj7" },
      { note: 64, startSeconds: 8.4, durationSeconds: 3.0, label: "Fmaj7" },
    ],
  },
  {
    id: "chord_lvl4_dark_trap_minor",
    title: "Dark Trap Minor (Cm – Ab – Fm – G)",
    category: "chord",
    level: 4,
    icon: "🕷️",
    bpm: 135,
    difficulty: "Intermédiaire+",
    description: "Progression mineure dramatique et ténébreuse avec accords suspendus.",
    durationSeconds: 22.0,
    recommendedEngine: "Pulse",
    recommendedPatch: "Virtual Analog Saw Lead",
    notes: [
      // Cm (60, 63, 67)
      { note: 60, startSeconds: 0.0, durationSeconds: 1.8, label: "Cm" },
      { note: 63, startSeconds: 0.0, durationSeconds: 1.8, label: "Cm" },
      { note: 67, startSeconds: 0.0, durationSeconds: 1.8, label: "Cm" },
      // Ab (56, 60, 63)
      { note: 56, startSeconds: 2.0, durationSeconds: 1.8, label: "Ab" },
      { note: 60, startSeconds: 2.0, durationSeconds: 1.8, label: "Ab" },
      { note: 63, startSeconds: 2.0, durationSeconds: 1.8, label: "Ab" },
      // Fm (53, 56, 60)
      { note: 53, startSeconds: 4.0, durationSeconds: 1.8, label: "Fm" },
      { note: 56, startSeconds: 4.0, durationSeconds: 1.8, label: "Fm" },
      { note: 60, startSeconds: 4.0, durationSeconds: 1.8, label: "Fm" },
      // G Maj (55, 59, 62)
      { note: 55, startSeconds: 6.0, durationSeconds: 2.5, label: "G Maj" },
      { note: 59, startSeconds: 6.0, durationSeconds: 2.5, label: "G Maj" },
      { note: 62, startSeconds: 6.0, durationSeconds: 2.5, label: "G Maj" },
    ],
  },
  {
    id: "chord_lvl5_nudisco_stabs",
    title: "House & Nu-Disco Stabs (Dm9 – Gm7 – C9 – Fmaj7)",
    category: "chord",
    level: 5,
    icon: "🕺",
    bpm: 122,
    difficulty: "Avancé",
    description: "Accords coupés très courts (staccato) et syncopés sur les contretemps de la basse.",
    durationSeconds: 20.0,
    recommendedEngine: "FM",
    recommendedPatch: "Acid Sequence",
    notes: [
      // Dm9 stab (62, 65, 69, 72, 76)
      { note: 62, startSeconds: 0.0, durationSeconds: 0.4, label: "Dm9" },
      { note: 65, startSeconds: 0.0, durationSeconds: 0.4, label: "Dm9" },
      { note: 69, startSeconds: 0.0, durationSeconds: 0.4, label: "Dm9" },
      { note: 72, startSeconds: 0.0, durationSeconds: 0.4, label: "Dm9" },
      // Gm7 (55, 58, 62, 65)
      { note: 55, startSeconds: 1.0, durationSeconds: 0.4, label: "Gm7" },
      { note: 58, startSeconds: 1.0, durationSeconds: 0.4, label: "Gm7" },
      { note: 62, startSeconds: 1.0, durationSeconds: 0.4, label: "Gm7" },
      { note: 65, startSeconds: 1.0, durationSeconds: 0.4, label: "Gm7" },
      // C9 (60, 64, 67, 70, 74)
      { note: 60, startSeconds: 2.0, durationSeconds: 0.4, label: "C9" },
      { note: 64, startSeconds: 2.0, durationSeconds: 0.4, label: "C9" },
      { note: 67, startSeconds: 2.0, durationSeconds: 0.4, label: "C9" },
      { note: 70, startSeconds: 2.0, durationSeconds: 0.4, label: "C9" },
      // Fmaj7 (53, 57, 60, 64)
      { note: 53, startSeconds: 3.0, durationSeconds: 0.6, label: "Fmaj7" },
      { note: 57, startSeconds: 3.0, durationSeconds: 0.6, label: "Fmaj7" },
      { note: 60, startSeconds: 3.0, durationSeconds: 0.6, label: "Fmaj7" },
      { note: 64, startSeconds: 3.0, durationSeconds: 0.6, label: "Fmaj7" },
    ],
  },
  {
    id: "chord_lvl6_amapiano_deep_chords",
    title: "Amapiano Deep Lush Chords (Ebm7 – Bbm7 – Abm7)",
    category: "chord",
    level: 6,
    icon: "🇿🇦",
    bpm: 112,
    difficulty: "Avancé+",
    description: "Harmonie sud-africaine suave et profonde avec renversements soyeux pour Rhodes.",
    durationSeconds: 24.0,
    recommendedEngine: "Cluster",
    recommendedPatch: "Tape Velvet Keys",
    notes: [
      // Ebm7 (63, 66, 70, 73)
      { note: 63, startSeconds: 0.0, durationSeconds: 2.5, label: "Ebm7" },
      { note: 66, startSeconds: 0.0, durationSeconds: 2.5, label: "Ebm7" },
      { note: 70, startSeconds: 0.0, durationSeconds: 2.5, label: "Ebm7" },
      { note: 73, startSeconds: 0.0, durationSeconds: 2.5, label: "Ebm7" },
      // Bbm7 (58, 61, 65, 68)
      { note: 58, startSeconds: 2.8, durationSeconds: 2.5, label: "Bbm7" },
      { note: 61, startSeconds: 2.8, durationSeconds: 2.5, label: "Bbm7" },
      { note: 65, startSeconds: 2.8, durationSeconds: 2.5, label: "Bbm7" },
      { note: 68, startSeconds: 2.8, durationSeconds: 2.5, label: "Bbm7" },
      // Abm7 (56, 59, 63, 66)
      { note: 56, startSeconds: 5.6, durationSeconds: 3.2, label: "Abm7" },
      { note: 59, startSeconds: 5.6, durationSeconds: 3.2, label: "Abm7" },
      { note: 63, startSeconds: 5.6, durationSeconds: 3.2, label: "Abm7" },
      { note: 66, startSeconds: 5.6, durationSeconds: 3.2, label: "Abm7" },
    ],
  },
  {
    id: "chord_lvl7_neosoul_voicings",
    title: "Neo-Soul 9th & 11th Voicings (Dmaj9 – C#m7 – Bm9)",
    category: "chord",
    level: 7,
    icon: "🎷",
    bpm: 86,
    difficulty: "Pro",
    description: "Voicings 4 & 5 voix enrichis de 9èmes majeures et d'extensions soyeuses (Robert Glasper style).",
    durationSeconds: 26.0,
    recommendedEngine: "FM",
    recommendedPatch: "Dream Poly Synth",
    notes: [
      // Dmaj9 (62, 66, 69, 73, 76)
      { note: 62, startSeconds: 0.0, durationSeconds: 2.6, label: "Dmaj9" },
      { note: 66, startSeconds: 0.0, durationSeconds: 2.6, label: "Dmaj9" },
      { note: 69, startSeconds: 0.0, durationSeconds: 2.6, label: "Dmaj9" },
      { note: 73, startSeconds: 0.0, durationSeconds: 2.6, label: "Dmaj9" },
      // C#m7 (61, 64, 68, 71)
      { note: 61, startSeconds: 3.0, durationSeconds: 2.6, label: "C#m7" },
      { note: 64, startSeconds: 3.0, durationSeconds: 2.6, label: "C#m7" },
      { note: 68, startSeconds: 3.0, durationSeconds: 2.6, label: "C#m7" },
      { note: 71, startSeconds: 3.0, durationSeconds: 2.6, label: "C#m7" },
      // Bm9 (59, 62, 66, 69, 73)
      { note: 59, startSeconds: 6.0, durationSeconds: 3.2, label: "Bm9" },
      { note: 62, startSeconds: 6.0, durationSeconds: 3.2, label: "Bm9" },
      { note: 66, startSeconds: 6.0, durationSeconds: 3.2, label: "Bm9" },
      { note: 69, startSeconds: 6.0, durationSeconds: 3.2, label: "Bm9" },
    ],
  },
  {
    id: "chord_lvl8_futurebass_pumping",
    title: "Future Bass Sidechained Progression",
    category: "chord",
    level: 8,
    icon: "⚡",
    bpm: 150,
    difficulty: "Pro+",
    description: "Accords supersaw syncopés à la croche avec pulsation sidechain agressive.",
    durationSeconds: 24.0,
    recommendedEngine: "Pulse",
    recommendedPatch: "Virtual Analog Saw Lead",
    notes: [
      // Fmaj7 pump
      { note: 53, startSeconds: 0.0, durationSeconds: 0.35, label: "Fmaj7" },
      { note: 60, startSeconds: 0.0, durationSeconds: 0.35, label: "Fmaj7" },
      { note: 64, startSeconds: 0.0, durationSeconds: 0.35, label: "Fmaj7" },
      { note: 67, startSeconds: 0.0, durationSeconds: 0.35, label: "Fmaj7" },
      // Hit 2
      { note: 53, startSeconds: 0.6, durationSeconds: 0.35, label: "Fmaj7" },
      { note: 60, startSeconds: 0.6, durationSeconds: 0.35, label: "Fmaj7" },
      { note: 64, startSeconds: 0.6, durationSeconds: 0.35, label: "Fmaj7" },
      { note: 67, startSeconds: 0.6, durationSeconds: 0.35, label: "Fmaj7" },
      // G Maj
      { note: 55, startSeconds: 1.2, durationSeconds: 0.35, label: "G Maj" },
      { note: 59, startSeconds: 1.2, durationSeconds: 0.35, label: "G Maj" },
      { note: 62, startSeconds: 1.2, durationSeconds: 0.35, label: "G Maj" },
      // Am7
      { note: 57, startSeconds: 2.0, durationSeconds: 0.5, label: "Am7" },
      { note: 60, startSeconds: 2.0, durationSeconds: 0.5, label: "Am7" },
      { note: 64, startSeconds: 2.0, durationSeconds: 0.5, label: "Am7" },
      { note: 67, startSeconds: 2.0, durationSeconds: 0.5, label: "Am7" },
    ],
  },
  {
    id: "chord_lvl9_coltrane_giant_steps",
    title: "Jazz Coltrane Giant Steps Modulations",
    category: "chord",
    level: 9,
    icon: "🎷",
    bpm: 110,
    difficulty: "Expert",
    description: "Les modulations majeures mythiques de John Coltrane en cycles de tierces majeures (B - G - Eb).",
    durationSeconds: 28.0,
    recommendedEngine: "FM",
    recommendedPatch: "Dream Poly Synth",
    notes: [
      // Bmaj7 (59, 63, 66, 70)
      { note: 59, startSeconds: 0.0, durationSeconds: 1.8, label: "Bmaj7" },
      { note: 63, startSeconds: 0.0, durationSeconds: 1.8, label: "Bmaj7" },
      { note: 66, startSeconds: 0.0, durationSeconds: 1.8, label: "Bmaj7" },
      { note: 70, startSeconds: 0.0, durationSeconds: 1.8, label: "Bmaj7" },
      // D7 (62, 66, 69, 72)
      { note: 62, startSeconds: 2.0, durationSeconds: 1.8, label: "D7" },
      { note: 66, startSeconds: 2.0, durationSeconds: 1.8, label: "D7" },
      { note: 69, startSeconds: 2.0, durationSeconds: 1.8, label: "D7" },
      { note: 72, startSeconds: 2.0, durationSeconds: 1.8, label: "D7" },
      // Gmaj7 (55, 59, 62, 66)
      { note: 55, startSeconds: 4.0, durationSeconds: 1.8, label: "Gmaj7" },
      { note: 59, startSeconds: 4.0, durationSeconds: 1.8, label: "Gmaj7" },
      { note: 62, startSeconds: 4.0, durationSeconds: 1.8, label: "Gmaj7" },
      { note: 66, startSeconds: 4.0, durationSeconds: 1.8, label: "Gmaj7" },
      // Bb7 (58, 62, 65, 68)
      { note: 58, startSeconds: 6.0, durationSeconds: 1.8, label: "Bb7" },
      { note: 62, startSeconds: 6.0, durationSeconds: 1.8, label: "Bb7" },
      { note: 65, startSeconds: 6.0, durationSeconds: 1.8, label: "Bb7" },
      { note: 68, startSeconds: 6.0, durationSeconds: 1.8, label: "Bb7" },
      // Ebmaj7 (63, 67, 70, 74)
      { note: 63, startSeconds: 8.0, durationSeconds: 2.5, label: "Ebmaj7" },
      { note: 67, startSeconds: 8.0, durationSeconds: 2.5, label: "Ebmaj7" },
      { note: 70, startSeconds: 8.0, durationSeconds: 2.5, label: "Ebmaj7" },
      { note: 74, startSeconds: 8.0, durationSeconds: 2.5, label: "Ebmaj7" },
    ],
  },
  {
    id: "chord_lvl10_gospel_reharm_virtuoso",
    title: "Cinematic Gospel & Reharmonisation Avancée",
    category: "chord",
    level: 10,
    icon: "👑",
    bpm: 78,
    difficulty: "Grand Maître",
    description: "Reharmonisation complexe avec accords diminués de passage, altérations de quintes et accords à 5 notes.",
    durationSeconds: 32.0,
    recommendedEngine: "Cluster",
    recommendedPatch: "Tape Velvet Keys",
    notes: [
      // Cmaj9 (60, 64, 67, 71, 74)
      { note: 60, startSeconds: 0.0, durationSeconds: 2.8, label: "Cmaj9" },
      { note: 64, startSeconds: 0.0, durationSeconds: 2.8, label: "Cmaj9" },
      { note: 67, startSeconds: 0.0, durationSeconds: 2.8, label: "Cmaj9" },
      { note: 71, startSeconds: 0.0, durationSeconds: 2.8, label: "Cmaj9" },
      // C#dim7 (61, 64, 67, 70)
      { note: 61, startSeconds: 3.2, durationSeconds: 2.6, label: "C#dim7" },
      { note: 64, startSeconds: 3.2, durationSeconds: 2.6, label: "C#dim7" },
      { note: 67, startSeconds: 3.2, durationSeconds: 2.6, label: "C#dim7" },
      { note: 70, startSeconds: 3.2, durationSeconds: 2.6, label: "C#dim7" },
      // Dm11 (62, 65, 69, 72, 77)
      { note: 62, startSeconds: 6.2, durationSeconds: 2.6, label: "Dm11" },
      { note: 65, startSeconds: 6.2, durationSeconds: 2.6, label: "Dm11" },
      { note: 69, startSeconds: 6.2, durationSeconds: 2.6, label: "Dm11" },
      { note: 72, startSeconds: 6.2, durationSeconds: 2.6, label: "Dm11" },
      // G7alt (55, 59, 62, 66, 70)
      { note: 55, startSeconds: 9.2, durationSeconds: 3.5, label: "G7alt" },
      { note: 59, startSeconds: 9.2, durationSeconds: 3.5, label: "G7alt" },
      { note: 66, startSeconds: 9.2, durationSeconds: 3.5, label: "G7alt" },
      { note: 70, startSeconds: 9.2, durationSeconds: 3.5, label: "G7alt" },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // CATÉGORIE 3 : FINGER DRUMMING OP-1 (10 EXERCICES / NIVEAUX 1 À 10)
  // Mapping fidèle OP-1 : 53=Kick1, 54=Kick2/808, 55=Snare1, 56=Clap, 57=Hat, 59=OpenHat, 60=Crash, 65=Shaker, 75=Vox, 76=Sub
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "drum_lvl1_basic_groove",
    title: "Finger Drumming : Initiation Pulse (Kick 53, Snare 55 & Hat 57)",
    category: "drum",
    level: 1,
    icon: "🥁",
    bpm: 85,
    difficulty: "Débutant",
    description: "Apprentissage de la coordination des deux mains sur les touches Kick (53), Snare (55) et Closed Hat (57).",
    durationSeconds: 18.0,
    recommendedEngine: "Drum",
    recommendedPatch: "Kit Drum OP-1 Standard",
    notes: [
      { note: 53, startSeconds: 0.0, durationSeconds: 0.25, label: "Kick (53)" },
      { note: 57, startSeconds: 0.0, durationSeconds: 0.2, label: "Hat (57)" },
      { note: 57, startSeconds: 0.7, durationSeconds: 0.2, label: "Hat (57)" },
      { note: 55, startSeconds: 1.4, durationSeconds: 0.25, label: "Snare (55)" },
      { note: 57, startSeconds: 1.4, durationSeconds: 0.2, label: "Hat (57)" },
      { note: 57, startSeconds: 2.1, durationSeconds: 0.2, label: "Hat (57)" },
      // Mesure 2
      { note: 53, startSeconds: 2.8, durationSeconds: 0.25, label: "Kick (53)" },
      { note: 57, startSeconds: 2.8, durationSeconds: 0.2, label: "Hat (57)" },
      { note: 57, startSeconds: 3.5, durationSeconds: 0.2, label: "Hat (57)" },
      { note: 55, startSeconds: 4.2, durationSeconds: 0.25, label: "Snare (55)" },
      { note: 57, startSeconds: 4.2, durationSeconds: 0.2, label: "Hat (57)" },
      { note: 57, startSeconds: 4.9, durationSeconds: 0.2, label: "Hat (57)" },
    ],
  },
  {
    id: "drum_lvl2_boombap_90s",
    title: "Finger Drumming : Boom Bap Hip-Hop 90s NYC",
    category: "drum",
    level: 2,
    icon: "🎧",
    bpm: 90,
    difficulty: "Débutant+",
    description: "Le groove intemporel de New York : double frappe de Kick et Open Hat (59) sur le 4e temps.",
    durationSeconds: 22.0,
    recommendedEngine: "Drum",
    recommendedPatch: "Kit Drum OP-1 Standard",
    notes: [
      { note: 53, startSeconds: 0.0, durationSeconds: 0.2, label: "Kick" },
      { note: 57, startSeconds: 0.0, durationSeconds: 0.15, label: "Hat" },
      { note: 57, startSeconds: 0.33, durationSeconds: 0.15, label: "Hat" },
      { note: 55, startSeconds: 0.66, durationSeconds: 0.2, label: "Snare" },
      { note: 57, startSeconds: 0.66, durationSeconds: 0.15, label: "Hat" },
      { note: 53, startSeconds: 1.15, durationSeconds: 0.2, label: "Kick" },
      { note: 53, startSeconds: 1.33, durationSeconds: 0.2, label: "Kick" },
      { note: 57, startSeconds: 1.33, durationSeconds: 0.15, label: "Hat" },
      { note: 55, startSeconds: 1.66, durationSeconds: 0.2, label: "Snare" },
      { note: 59, startSeconds: 2.0, durationSeconds: 0.3, label: "Open Hat" },
      // Cycle 2 avec Crash
      { note: 53, startSeconds: 2.33, durationSeconds: 0.2, label: "Kick" },
      { note: 60, startSeconds: 2.33, durationSeconds: 0.5, label: "Crash (60)" },
      { note: 55, startSeconds: 3.0, durationSeconds: 0.2, label: "Snare" },
      { note: 53, startSeconds: 3.66, durationSeconds: 0.2, label: "Kick" },
      { note: 55, startSeconds: 4.0, durationSeconds: 0.2, label: "Snare" },
      { note: 56, startSeconds: 4.0, durationSeconds: 0.2, label: "Clap" },
    ],
  },
  {
    id: "drum_lvl3_french_house_909",
    title: "Finger Drumming : French House & 909 4-on-the-Floor",
    category: "drum",
    level: 3,
    icon: "🪩",
    bpm: 124,
    difficulty: "Intermédiaire",
    description: "Kick régulier à la noire (53), Clap puissant au 2/4 (56) et Open Hi-Hat sur les contretemps (59).",
    durationSeconds: 22.0,
    recommendedEngine: "Drum",
    recommendedPatch: "House 909 Kit",
    notes: [
      { note: 53, startSeconds: 0.0, durationSeconds: 0.2, label: "Kick" },
      { note: 59, startSeconds: 0.24, durationSeconds: 0.2, label: "Open Hat" },
      { note: 53, startSeconds: 0.48, durationSeconds: 0.2, label: "Kick" },
      { note: 56, startSeconds: 0.48, durationSeconds: 0.2, label: "Clap" },
      { note: 59, startSeconds: 0.72, durationSeconds: 0.2, label: "Open Hat" },
      { note: 53, startSeconds: 0.96, durationSeconds: 0.2, label: "Kick" },
      { note: 59, startSeconds: 1.2, durationSeconds: 0.2, label: "Open Hat" },
      { note: 53, startSeconds: 1.44, durationSeconds: 0.2, label: "Kick" },
      { note: 56, startSeconds: 1.44, durationSeconds: 0.2, label: "Clap" },
      { note: 65, startSeconds: 1.68, durationSeconds: 0.15, label: "Shaker" },
    ],
  },
  {
    id: "drum_lvl4_lofi_dusty_scratch",
    title: "Finger Drumming : Lo-Fi Vinyl Dusty Beat & Scratch",
    category: "drum",
    level: 4,
    icon: "☕",
    bpm: 80,
    difficulty: "Intermédiaire+",
    description: "Atmosphère chaleureuse avec touches de scratch vinyle (73) et rimshots subtils (56).",
    durationSeconds: 24.0,
    recommendedEngine: "Drum",
    recommendedPatch: "Lo-Fi Vintage Vinyl",
    notes: [
      { note: 53, startSeconds: 0.0, durationSeconds: 0.25, label: "Kick" },
      { note: 73, startSeconds: 0.0, durationSeconds: 0.3, label: "Scratch" },
      { note: 58, startSeconds: 0.38, durationSeconds: 0.15, label: "Half Hat" },
      { note: 56, startSeconds: 0.75, durationSeconds: 0.25, label: "Rimshot" },
      { note: 58, startSeconds: 1.12, durationSeconds: 0.15, label: "Half Hat" },
      { note: 53, startSeconds: 1.35, durationSeconds: 0.25, label: "Kick" },
      { note: 58, startSeconds: 1.5, durationSeconds: 0.15, label: "Half Hat" },
      { note: 56, startSeconds: 1.88, durationSeconds: 0.25, label: "Rimshot" },
      { note: 67, startSeconds: 2.1, durationSeconds: 0.2, label: "Woodblock" },
      { note: 59, startSeconds: 2.25, durationSeconds: 0.3, label: "Open Hat" },
    ],
  },
  {
    id: "drum_lvl5_afrobeat_shakers_congas",
    title: "Finger Drumming : Afrobeat Shakers & Congas Groove",
    category: "drum",
    level: 5,
    icon: "🪘",
    bpm: 104,
    difficulty: "Avancé",
    description: "Polyrythmie africaine : Shaker continu (65), Congas aiguës/graves (69/70) et Claves (68).",
    durationSeconds: 24.0,
    recommendedEngine: "Drum",
    recommendedPatch: "Kit Drum OP-1 Standard",
    notes: [
      { note: 53, startSeconds: 0.0, durationSeconds: 0.2, label: "Kick" },
      { note: 65, startSeconds: 0.0, durationSeconds: 0.12, label: "Shaker" },
      { note: 65, startSeconds: 0.28, durationSeconds: 0.12, label: "Shaker" },
      { note: 69, startSeconds: 0.42, durationSeconds: 0.2, label: "Conga Low" },
      { note: 65, startSeconds: 0.57, durationSeconds: 0.12, label: "Shaker" },
      { note: 56, startSeconds: 0.57, durationSeconds: 0.2, label: "Rimshot" },
      { note: 70, startSeconds: 0.75, durationSeconds: 0.2, label: "Conga High" },
      { note: 68, startSeconds: 0.95, durationSeconds: 0.15, label: "Claves" },
      { note: 53, startSeconds: 1.15, durationSeconds: 0.2, label: "Kick" },
      { note: 65, startSeconds: 1.15, durationSeconds: 0.12, label: "Shaker" },
      { note: 56, startSeconds: 1.44, durationSeconds: 0.2, label: "Rimshot" },
    ],
  },
  {
    id: "drum_lvl6_amapiano_logdrum",
    title: "Finger Drumming : Amapiano Log Drum & Shaker",
    category: "drum",
    level: 6,
    icon: "🪵",
    bpm: 112,
    difficulty: "Avancé+",
    description: "Le roulement syncopé de Log Drum basse (Sub 76), Shaker rapide (65) et Rimshot décalé (56).",
    durationSeconds: 24.0,
    recommendedEngine: "Drum",
    recommendedPatch: "Kit Drum OP-1 Standard",
    notes: [
      { note: 76, startSeconds: 0.0, durationSeconds: 0.3, label: "Log Drum (76)" },
      { note: 65, startSeconds: 0.0, durationSeconds: 0.1, label: "Shaker" },
      { note: 65, startSeconds: 0.26, durationSeconds: 0.1, label: "Shaker" },
      { note: 76, startSeconds: 0.38, durationSeconds: 0.2, label: "Log Drum" },
      { note: 56, startSeconds: 0.53, durationSeconds: 0.2, label: "Rimshot" },
      { note: 65, startSeconds: 0.53, durationSeconds: 0.1, label: "Shaker" },
      { note: 76, startSeconds: 0.79, durationSeconds: 0.3, label: "Log Drum" },
      { note: 76, startSeconds: 1.05, durationSeconds: 0.2, label: "Log Drum" },
      { note: 56, startSeconds: 1.32, durationSeconds: 0.2, label: "Rimshot" },
    ],
  },
  {
    id: "drum_lvl7_trap_808_rolls",
    title: "Finger Drumming : Modern Trap & 808 Rolls",
    category: "drum",
    level: 7,
    icon: "⚡",
    bpm: 140,
    difficulty: "Pro",
    description: "Basse lourde 808 (54), Rimshot sec (56), Hi-Hats rapides (57) et Vox Chop d'accent (75).",
    durationSeconds: 26.0,
    recommendedEngine: "Drum",
    recommendedPatch: "Trap 808 Modern Kit",
    notes: [
      { note: 54, startSeconds: 0.0, durationSeconds: 0.5, label: "808 Kick" },
      { note: 57, startSeconds: 0.0, durationSeconds: 0.1, label: "Hat" },
      { note: 57, startSeconds: 0.21, durationSeconds: 0.1, label: "Hat" },
      { note: 57, startSeconds: 0.42, durationSeconds: 0.1, label: "Hat" },
      { note: 56, startSeconds: 0.64, durationSeconds: 0.2, label: "Rimshot" },
      { note: 57, startSeconds: 0.85, durationSeconds: 0.08, label: "Hat Roll" },
      { note: 57, startSeconds: 0.95, durationSeconds: 0.08, label: "Hat Roll" },
      { note: 57, startSeconds: 1.05, durationSeconds: 0.08, label: "Hat Roll" },
      { note: 54, startSeconds: 1.15, durationSeconds: 0.4, label: "808 Kick" },
      { note: 56, startSeconds: 1.5, durationSeconds: 0.2, label: "Rimshot" },
      { note: 75, startSeconds: 1.7, durationSeconds: 0.3, label: "Vox Hit (75)" },
    ],
  },
  {
    id: "drum_lvl8_uk_drill_sliding_hats",
    title: "Finger Drumming : UK Drill Sliding Hats & Counter-Snare",
    category: "drum",
    level: 8,
    icon: "🗡️",
    bpm: 142,
    difficulty: "Pro+",
    description: "Pattern asymétrique typique de Londres avec contre-caisses claires et triolets de charlestons.",
    durationSeconds: 28.0,
    recommendedEngine: "Drum",
    recommendedPatch: "Trap 808 Modern Kit",
    notes: [
      { note: 53, startSeconds: 0.0, durationSeconds: 0.2, label: "Kick" },
      { note: 57, startSeconds: 0.0, durationSeconds: 0.1, label: "Hat" },
      { note: 57, startSeconds: 0.2, durationSeconds: 0.1, label: "Hat" },
      { note: 56, startSeconds: 0.42, durationSeconds: 0.15, label: "Ghost Rim" },
      { note: 55, startSeconds: 0.63, durationSeconds: 0.25, label: "Main Snare" },
      { note: 57, startSeconds: 0.84, durationSeconds: 0.1, label: "Hat" },
      { note: 53, startSeconds: 1.05, durationSeconds: 0.2, label: "Kick" },
      { note: 58, startSeconds: 1.26, durationSeconds: 0.12, label: "Slide Hat" },
      { note: 55, startSeconds: 1.47, durationSeconds: 0.25, label: "Counter Snare" },
    ],
  },
  {
    id: "drum_lvl9_jersey_baile_funk",
    title: "Finger Drumming : Jersey Club & Baile Funk Fast Triplets",
    category: "drum",
    level: 9,
    icon: "🔥",
    bpm: 132,
    difficulty: "Expert",
    description: "Le rythme bondissant 5-kick de Jersey City avec bruits de ressorts (74) et Vox shouts (75).",
    durationSeconds: 28.0,
    recommendedEngine: "Drum",
    recommendedPatch: "Kit Drum OP-1 Standard",
    notes: [
      { note: 53, startSeconds: 0.0, durationSeconds: 0.15, label: "Kick" },
      { note: 53, startSeconds: 0.22, durationSeconds: 0.15, label: "Kick" },
      { note: 53, startSeconds: 0.45, durationSeconds: 0.15, label: "Kick" },
      { note: 53, startSeconds: 0.58, durationSeconds: 0.15, label: "Kick" },
      { note: 55, startSeconds: 0.68, durationSeconds: 0.2, label: "Snare" },
      { note: 74, startSeconds: 0.9, durationSeconds: 0.15, label: "Bed Squeak (74)" },
      { note: 75, startSeconds: 1.13, durationSeconds: 0.2, label: "Vox Hit" },
      { note: 53, startSeconds: 1.35, durationSeconds: 0.15, label: "Kick" },
      { note: 55, startSeconds: 1.58, durationSeconds: 0.2, label: "Snare" },
    ],
  },
  {
    id: "drum_lvl10_jungle_amen_break",
    title: "Finger Drumming : Drum & Bass Jungle 168 BPM Amen Break",
    category: "drum",
    level: 10,
    icon: "💥",
    bpm: 168,
    difficulty: "Grand Maître",
    description: "Vitesse et dextérité extrêmes : le mythique Amen Break reconstitué note par note à 168 BPM !",
    durationSeconds: 30.0,
    recommendedEngine: "Drum",
    recommendedPatch: "Funk Breaks 70s",
    notes: [
      { note: 53, startSeconds: 0.0, durationSeconds: 0.12, label: "Kick" },
      { note: 61, startSeconds: 0.0, durationSeconds: 0.1, label: "Ride" },
      { note: 55, startSeconds: 0.18, durationSeconds: 0.1, label: "Ghost Snare" },
      { note: 55, startSeconds: 0.36, durationSeconds: 0.15, label: "Main Snare" },
      { note: 61, startSeconds: 0.36, durationSeconds: 0.1, label: "Ride" },
      { note: 53, startSeconds: 0.54, durationSeconds: 0.12, label: "Kick" },
      { note: 53, startSeconds: 0.72, durationSeconds: 0.12, label: "Kick" },
      { note: 55, startSeconds: 0.9, durationSeconds: 0.15, label: "Main Snare" },
      { note: 60, startSeconds: 1.08, durationSeconds: 0.3, label: "Crash (60)" },
      { note: 55, startSeconds: 1.26, durationSeconds: 0.1, label: "Ghost Snare" },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // CATÉGORIE 4 : ARCADE & STYLES MODERNES (10 EXERCICES / NIVEAUX 1 À 10)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "arcade_lvl1_gameboy_chiptune",
    title: "Gameboy Chiptune 8-Bit Nostalgia",
    category: "arcade",
    level: 1,
    icon: "👾",
    bpm: 110,
    difficulty: "Débutant",
    description: "Thème rétro carré et entraînant façon console portable vintage des années 90.",
    durationSeconds: 18.0,
    recommendedEngine: "Pulse",
    recommendedPatch: "Acid Bassline 303",
    notes: [
      { note: 60, startSeconds: 0.0, durationSeconds: 0.3, label: "C4" },
      { note: 64, startSeconds: 0.35, durationSeconds: 0.3, label: "E4" },
      { note: 67, startSeconds: 0.7, durationSeconds: 0.5, label: "G4" },
      { note: 72, startSeconds: 1.3, durationSeconds: 0.6, label: "C5" },
      { note: 67, startSeconds: 2.0, durationSeconds: 0.3, label: "G4" },
      { note: 64, startSeconds: 2.35, durationSeconds: 0.3, label: "E4" },
      { note: 60, startSeconds: 2.7, durationSeconds: 1.2, label: "C4" },
    ],
  },
  {
    id: "arcade_lvl2_tetris_korobeiniki",
    title: "Korobeiniki (Tetris Theme A Legend)",
    category: "arcade",
    level: 2,
    icon: "🕹️",
    bpm: 124,
    difficulty: "Débutant+",
    description: "L'hymne légendaire des briques qui tombent, référence absolue du jeu vidéo musical.",
    durationSeconds: 22.0,
    recommendedEngine: "Pulse",
    recommendedPatch: "Virtual Analog Saw Lead",
    notes: [
      { note: 64, startSeconds: 0.0, durationSeconds: 0.45, label: "E4" },
      { note: 59, startSeconds: 0.5, durationSeconds: 0.22, label: "B3" },
      { note: 60, startSeconds: 0.75, durationSeconds: 0.22, label: "C4" },
      { note: 62, startSeconds: 1.0, durationSeconds: 0.45, label: "D4" },
      { note: 60, startSeconds: 1.5, durationSeconds: 0.22, label: "C4" },
      { note: 59, startSeconds: 1.75, durationSeconds: 0.22, label: "B3" },
      { note: 57, startSeconds: 2.0, durationSeconds: 0.45, label: "A3" },
      { note: 57, startSeconds: 2.5, durationSeconds: 0.22, label: "A3" },
      { note: 60, startSeconds: 2.75, durationSeconds: 0.22, label: "C4" },
      { note: 64, startSeconds: 3.0, durationSeconds: 0.45, label: "E4" },
      { note: 62, startSeconds: 3.5, durationSeconds: 0.22, label: "D4" },
      { note: 60, startSeconds: 3.75, durationSeconds: 0.22, label: "C4" },
      { note: 59, startSeconds: 4.0, durationSeconds: 0.8, label: "B3" },
    ],
  },
  {
    id: "arcade_lvl3_outrun_synthwave",
    title: "Outrun Retrowave Highway Chase",
    category: "arcade",
    level: 3,
    icon: "🏎️",
    bpm: 116,
    difficulty: "Intermédiaire",
    description: "Course-poursuite nocturne à bord d'une Testarossa néon sur l'autoroute de Miami.",
    durationSeconds: 24.0,
    recommendedEngine: "FM",
    recommendedPatch: "Acid Sequence",
    notes: [
      { note: 57, startSeconds: 0.0, durationSeconds: 0.2, label: "A3" },
      { note: 60, startSeconds: 0.22, durationSeconds: 0.2, label: "C4" },
      { note: 64, startSeconds: 0.44, durationSeconds: 0.2, label: "E4" },
      { note: 69, startSeconds: 0.66, durationSeconds: 0.4, label: "A4" },
      { note: 67, startSeconds: 1.1, durationSeconds: 0.2, label: "G4" },
      { note: 64, startSeconds: 1.32, durationSeconds: 0.2, label: "E4" },
      { note: 60, startSeconds: 1.54, durationSeconds: 0.2, label: "C4" },
      { note: 62, startSeconds: 1.76, durationSeconds: 0.4, label: "D4" },
      { note: 59, startSeconds: 2.2, durationSeconds: 0.2, label: "B3" },
      { note: 62, startSeconds: 2.42, durationSeconds: 0.2, label: "D4" },
      { note: 67, startSeconds: 2.64, durationSeconds: 0.4, label: "G4" },
    ],
  },
  {
    id: "arcade_lvl4_tokyo_drift_phonk",
    title: "Tokyo Drift Phonk Heavy Bass & Cowbell",
    category: "arcade",
    level: 4,
    icon: "🏁",
    bpm: 130,
    difficulty: "Intermédiaire+",
    description: "Drift urbain sous la pluie : cloche agressive (Cowbell 67) et basse saturée 808.",
    durationSeconds: 24.0,
    recommendedEngine: "Pulse",
    recommendedPatch: "Virtual Analog Saw Lead",
    notes: [
      { note: 67, startSeconds: 0.0, durationSeconds: 0.2, label: "Cowbell" },
      { note: 67, startSeconds: 0.25, durationSeconds: 0.2, label: "Cowbell" },
      { note: 70, startSeconds: 0.5, durationSeconds: 0.3, label: "High Bell" },
      { note: 67, startSeconds: 0.9, durationSeconds: 0.2, label: "Cowbell" },
      { note: 65, startSeconds: 1.15, durationSeconds: 0.2, label: "Bell F" },
      { note: 63, startSeconds: 1.4, durationSeconds: 0.4, label: "Bell Eb" },
      { note: 58, startSeconds: 1.9, durationSeconds: 0.5, label: "Sub Bass" },
      { note: 67, startSeconds: 2.5, durationSeconds: 0.2, label: "Cowbell" },
    ],
  },
  {
    id: "arcade_lvl5_daft_punk_celebration",
    title: "Daft Punk Tribute (One More Time / Aerodynamic)",
    category: "arcade",
    level: 5,
    icon: "🤖",
    bpm: 125,
    difficulty: "Avancé",
    description: "Hommage aux robots légendaires : riff festif filtré et solo de synthé étincelant.",
    durationSeconds: 26.0,
    recommendedEngine: "FM",
    recommendedPatch: "Dream Poly Synth",
    notes: [
      { note: 62, startSeconds: 0.0, durationSeconds: 0.2, label: "D4" },
      { note: 65, startSeconds: 0.24, durationSeconds: 0.2, label: "F4" },
      { note: 69, startSeconds: 0.48, durationSeconds: 0.35, label: "A4" },
      { note: 74, startSeconds: 0.96, durationSeconds: 0.5, label: "D5" },
      { note: 72, startSeconds: 1.5, durationSeconds: 0.25, label: "C5" },
      { note: 69, startSeconds: 1.8, durationSeconds: 0.25, label: "A4" },
      { note: 65, startSeconds: 2.1, durationSeconds: 0.3, label: "F4" },
      { note: 67, startSeconds: 2.5, durationSeconds: 0.8, label: "G4" },
    ],
  },
  {
    id: "arcade_lvl6_cyberpunk_boss_fight",
    title: "Cyberpunk Neon Boss Battle",
    category: "arcade",
    level: 6,
    icon: "🦾",
    bpm: 135,
    difficulty: "Avancé+",
    description: "Combat décisif au sommet d'une mégastructure : arpèges tranchants et percussions massives.",
    durationSeconds: 26.0,
    recommendedEngine: "Voltage",
    recommendedPatch: "Acid Bassline 303",
    notes: [
      { note: 57, startSeconds: 0.0, durationSeconds: 0.15, label: "A3" },
      { note: 60, startSeconds: 0.18, durationSeconds: 0.15, label: "C4" },
      { note: 63, startSeconds: 0.36, durationSeconds: 0.15, label: "Eb4" },
      { note: 66, startSeconds: 0.54, durationSeconds: 0.3, label: "F#4" },
      { note: 69, startSeconds: 0.9, durationSeconds: 0.2, label: "A4" },
      { note: 66, startSeconds: 1.15, durationSeconds: 0.2, label: "F#4" },
      { note: 63, startSeconds: 1.4, durationSeconds: 0.2, label: "Eb4" },
      { note: 60, startSeconds: 1.65, durationSeconds: 0.5, label: "C4" },
    ],
  },
  {
    id: "arcade_lvl7_hyperpop_speedcore",
    title: "Hyperpop Speedcore Glitch Anthem",
    category: "arcade",
    level: 7,
    icon: "⚡",
    bpm: 155,
    difficulty: "Pro",
    description: "Euphorie numérique à tempo survolté : trilles rapides et explosions de notes multicolores.",
    durationSeconds: 26.0,
    recommendedEngine: "Pulse",
    recommendedPatch: "Virtual Analog Saw Lead",
    notes: [
      { note: 65, startSeconds: 0.0, durationSeconds: 0.12, label: "F4" },
      { note: 69, startSeconds: 0.15, durationSeconds: 0.12, label: "A4" },
      { note: 72, startSeconds: 0.3, durationSeconds: 0.15, label: "C5" },
      { note: 76, startSeconds: 0.5, durationSeconds: 0.25, label: "E5" },
      { note: 77, startSeconds: 0.8, durationSeconds: 0.12, label: "F5" },
      { note: 76, startSeconds: 0.95, durationSeconds: 0.12, label: "E5" },
      { note: 72, startSeconds: 1.1, durationSeconds: 0.2, label: "C5" },
      { note: 69, startSeconds: 1.35, durationSeconds: 0.4, label: "A4" },
    ],
  },
  {
    id: "arcade_lvl8_kawaii_future_bass",
    title: "Kawaii Future Bass Drop",
    category: "arcade",
    level: 8,
    icon: "🌸",
    bpm: 148,
    difficulty: "Pro+",
    description: "Mélodie joyeuse et pétillante avec sauts d'intervalles expressifs et accords scintillants (Snail's House style).",
    durationSeconds: 28.0,
    recommendedEngine: "FM",
    recommendedPatch: "Dream Poly Synth",
    notes: [
      { note: 64, startSeconds: 0.0, durationSeconds: 0.15, label: "E4" },
      { note: 67, startSeconds: 0.18, durationSeconds: 0.15, label: "G4" },
      { note: 71, startSeconds: 0.36, durationSeconds: 0.2, label: "B4" },
      { note: 76, startSeconds: 0.6, durationSeconds: 0.45, label: "E5" },
      { note: 74, startSeconds: 1.15, durationSeconds: 0.18, label: "D5" },
      { note: 71, startSeconds: 1.38, durationSeconds: 0.18, label: "B4" },
      { note: 67, startSeconds: 1.6, durationSeconds: 0.4, label: "G4" },
      { note: 69, startSeconds: 2.1, durationSeconds: 0.7, label: "A4" },
    ],
  },
  {
    id: "arcade_lvl9_edm_festival_drop",
    title: "EDM Festival Big Room Drop",
    category: "arcade",
    level: 9,
    icon: "🎆",
    bpm: 128,
    difficulty: "Expert",
    description: "Montée en tension maximale et drop ravageur pour stades : saut de quintes et énergie brute.",
    durationSeconds: 30.0,
    recommendedEngine: "Pulse",
    recommendedPatch: "Virtual Analog Saw Lead",
    notes: [
      { note: 60, startSeconds: 0.0, durationSeconds: 0.18, label: "C4" },
      { note: 60, startSeconds: 0.22, durationSeconds: 0.18, label: "C4" },
      { note: 67, startSeconds: 0.44, durationSeconds: 0.2, label: "G4" },
      { note: 65, startSeconds: 0.7, durationSeconds: 0.2, label: "F4" },
      { note: 64, startSeconds: 0.95, durationSeconds: 0.2, label: "E4" },
      { note: 62, startSeconds: 1.2, durationSeconds: 0.3, label: "D4" },
      { note: 60, startSeconds: 1.6, durationSeconds: 0.6, label: "C4" },
    ],
  },
  {
    id: "arcade_lvl10_final_boss_rush",
    title: "Grand Maître Arcade Final Boss Rush",
    category: "arcade",
    level: 10,
    icon: "👑",
    bpm: 165,
    difficulty: "Grand Maître",
    description: "L'épreuve suprême : enchaînement frénétique de toutes les techniques (gammes, arpèges, percussions) à 165 BPM !",
    durationSeconds: 32.0,
    recommendedEngine: "Voltage",
    recommendedPatch: "Acid Sequence",
    notes: [
      { note: 57, startSeconds: 0.0, durationSeconds: 0.1, label: "A3" },
      { note: 60, startSeconds: 0.12, durationSeconds: 0.1, label: "C4" },
      { note: 64, startSeconds: 0.24, durationSeconds: 0.1, label: "E4" },
      { note: 69, startSeconds: 0.36, durationSeconds: 0.15, label: "A4" },
      { note: 72, startSeconds: 0.54, durationSeconds: 0.12, label: "C5" },
      { note: 76, startSeconds: 0.7, durationSeconds: 0.25, label: "E5" },
      { note: 74, startSeconds: 1.0, durationSeconds: 0.1, label: "D5" },
      { note: 72, startSeconds: 1.15, durationSeconds: 0.1, label: "C5" },
      { note: 69, startSeconds: 1.3, durationSeconds: 0.15, label: "A4" },
      { note: 67, startSeconds: 1.5, durationSeconds: 0.2, label: "G4" },
      { note: 64, startSeconds: 1.75, durationSeconds: 0.3, label: "E4" },
      { note: 60, startSeconds: 2.15, durationSeconds: 0.5, label: "C4" },
      { note: 57, startSeconds: 2.8, durationSeconds: 2.0, label: "A3" },
    ],
  },
];
